export enum FieldDataType {
    Abn = 'abn',
    Acn = 'acn',
    Attachment = 'attachment',
    Boolean = 'boolean',
    Currency = 'currency',
    Date = 'date',
    Email = 'email',
    Name = 'name',
    None = 'none',
    Number = 'number',
    NumberPlate = 'number plate',
    Password = 'password',
    Percent = 'percent',
    Phone = 'phone',
    Postcode = 'postcode',
    Repeating = 'repeating',
    Text = 'text',
    Time = 'time',
    Url = 'url',
}
