export enum FieldType {
    Attachment = 'attachment',
    Buttons = 'buttons',
    Checkbox = 'checkbox',
    Content = 'content',
    Currency = 'currency',
    DatePicker = 'date-picker',
    DropDownSelect = 'drop-down-select',
    Hidden = 'hidden',
    Iframe = 'iframe',
    Password = 'password',
    Radio = 'radio',
    Repeating = 'repeating',
    SearchSelect = 'search-select',
    SingleLineText = 'single-line-text',
    TextArea = 'text-area',
    Toggle = 'toggle',
    Webhook = 'webhook',
    Slider = 'slider',
}
