export enum DetailsListItemGroupCategoryType {
    ContactDetails = "Contact Details",
    Relationships = "Relationships",
    Dates = "Dates",
    Others = "Others",
    Details = "Details",
    Status = "Status",
    DataSources = "Data Sources",
    Template = "Template",
    Deployment = "Deployment",
    DeployedReleases = "Deployed Releases",
    AdditionalProperties = "Additional Properties",
    ApplicableDomainNames = "Applicable Domains Names",
    Account = 'Account',
    Claim = "Claim",
    Filters = "Filters",
    Quotes = "Quotes",
    Sort = "Sort",
    Optional = "Optional Data",
    Products = "Products",
    QuoteType = "Quote Type",
}
