export enum SortAndFilterBy {
    CreatedDate = "Created Date",
    LastModifiedDate = "Last Modified Date",
    TenantName = "Tenant Name",
    ProductName = "Product Name",
    RoleName = "Role Name",
    ReportName = "Report Name",
    IssuedDate = "Issued Date",
    InceptionDate = "Inception Date",
    ExpiryDate = "Expiry Date",
    LatestRenewalDate = "Latest Renewal Date",
    CancellationDate = "Cancellation Date",
    CustomerName = "Customer Name",
    PolicyNumber = "Policy Number",
    ClaimNumber = "Claim Number",
    OrganisationName = "Organisation Name",
    UserName = "User Name",
    PortalName = "Portal Name",
    SentDate = "Sent Date",
    ReleaseNumber = "Release Number",
    DataTableName = "DataTable Name",
}

export enum SortAndFilterByFieldName {
    CreatedDate = "CreatedTicksSinceEpoch",
    LastModifiedDate = "LastModifiedTicksSinceEpoch",
    CustomerFullName = "CustomerFullName",
    FullName = "FullName",
    PersonDisplayName = "PrimaryPerson.DisplayName",
    DisplayName = "DisplayName",
    Name = "Name",
    DetailsName = "Details.Name",
    IssuedDate = "IssuedTicksSinceEpoch",
    InceptionDate = "InceptionTicksSinceEpoch",
    ExpiryDate = "ExpiryTicksSinceEpoch",
    LatestRenewalDate = "LatestRenewalEffectiveTicksSinceEpoch",
    CancellationDate = "CancellationEffectiveTicksSinceEpoch",
    PolicyNumber = "PolicyNumber",
    ClaimNumber = "ClaimNumber",
    ReleaseNumber = "Number",
    DetailsLastModifiedDate = "Details.CreatedTicksSinceEpoch"
}
