//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBind.Persistence.ThirdPartyDataSets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NfidRepositoryScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NfidRepositoryScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBind.Persistence.ThirdPartyDataSets.NfidRepositoryScripts", typeof(NfidRepositoryScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE TABLE [Stage6]
        ///(
        ///    [Gnaf_Pid] [varchar](50) NULL,
        ///    [Flat_Number] [varchar](50) NULL,
        ///    [Number_First] [varchar](50) NULL,
        ///    [Number_Last] [varchar](50) NULL,
        ///    [Street_Name] [varchar](50) NULL,
        ///    [Street_Type] [varchar](50) NULL,
        ///    [Locality_Name] [varchar](50) NULL,
        ///    [State] [varchar](50) NULL,
        ///    [Postcode] [varchar](50) NULL,
        ///    [Elev] [varchar](50) NULL,
        ///    [Flood_Depth_20] [varchar](50) NULL,
        ///    [Flood_Depth_50] [varchar](50) NULL,
        ///    [Flood_Depth_100] [var [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateNfidTable {
            get {
                return ResourceManager.GetString("CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (
        ///		SELECT *
        ///FROM sys.indexes
        ///WHERE name = &apos;Index1_Stage6&apos;
        ///    AND object_id = OBJECT_ID(&apos;Nfid.Stage6&apos;)
        ///		)
        ///BEGIN
        ///    CREATE NONCLUSTERED INDEX Index1_Stage6 ON [Nfid].[Stage6] (
        ///		[Gnaf_Pid] ASC
        ///		,[Elev] ASC
        ///		,[Flood_Depth_20] ASC
        ///		,[Flood_Depth_50] ASC
        ///		,[Flood_Depth_100] ASC
        ///		,[Flood_Depth_Extreme] ASC
        ///		,[Latitude] ASC
        ///		,[Longitude] ASC
        ///		)
        ///		WITH (
        ///				SORT_IN_TEMPDB = OFF
        ///				,DROP_EXISTING = OFF
        ///				,ONLINE = OFF
        ///				) ON [PRIMARY];
        ///END
        ///.
        /// </summary>
        internal static string Nfid_Add_Index {
            get {
                return ResourceManager.GetString("Add_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Gnaf_Pid]
        ///      , [Flat_Number]
        ///      , [Number_First]
        ///      , [Number_Last]
        ///      , [Street_Name]
        ///      , [Street_Type]
        ///      , [Locality_Name]
        ///      , [State]
        ///      , [Postcode]
        ///      , [Elev]
        ///      , [Flood_Depth_20]
        ///      , [Flood_Depth_50]
        ///      , [Flood_Depth_100]
        ///      , [Flood_Depth_Extreme]
        ///      , [Flood_Ari_Gl]
        ///      , [Flood_Ari_Gl1M]
        ///      , [Flood_Ari_Gl2M]
        ///      , [Notes_Id]
        ///      , [Level_Nfid_Id]
        ///      , [Level_Fez_Id]
        ///      , [Flood_Code]
        ///      , [Floor_Height] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nfid_GetStage6ByGnafId {
            get {
                return ResourceManager.GetString("GetStage6ByGnafId", resourceCulture);
            }
        }
    }
}
