// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Addedreleasedetails : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Files", "Release_Id", "dbo.Releases");
            DropIndex("dbo.Files", new[] { "Release_Id" });
            CreateTable(
                "dbo.ReleaseDetails",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        SpreadsheetPath = c.String(),
                        ConfigurationJson = c.String(),
                        WorkflowJson = c.String(),
                        ExportsJson = c.String(),
                        CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            AddColumn("dbo.Releases", "Details_Id", c => c.Guid());
            AddColumn("dbo.Files", "ReleaseDetails_Id", c => c.Guid());
            CreateIndex("dbo.Releases", "Details_Id");
            CreateIndex("dbo.Files", "ReleaseDetails_Id");
            AddForeignKey("dbo.Files", "ReleaseDetails_Id", "dbo.ReleaseDetails", "Id");
            AddForeignKey("dbo.Releases", "Details_Id", "dbo.ReleaseDetails", "Id");
            DropColumn("dbo.Releases", "SpreadsheetPath");
            DropColumn("dbo.Files", "Release_Id");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Files", "Release_Id", c => c.Guid());
            AddColumn("dbo.Releases", "SpreadsheetPath", c => c.String());
            DropForeignKey("dbo.Releases", "Details_Id", "dbo.ReleaseDetails");
            DropForeignKey("dbo.Files", "ReleaseDetails_Id", "dbo.ReleaseDetails");
            DropIndex("dbo.Files", new[] { "ReleaseDetails_Id" });
            DropIndex("dbo.Releases", new[] { "Details_Id" });
            DropColumn("dbo.Files", "ReleaseDetails_Id");
            DropColumn("dbo.Releases", "Details_Id");
            DropTable("dbo.ReleaseDetails");
            CreateIndex("dbo.Files", "Release_Id");
            AddForeignKey("dbo.Files", "Release_Id", "dbo.Releases", "Id");
        }
    }
}
