// <auto-generated />
namespace UBind.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addeduniquereleasenumbers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addeduniquereleasenumbers));
        
        string IMigrationMetadata.Id
        {
            get { return "201709290630053_Added unique release numbers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
