// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Addedapplicationpasswords : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.ApplicationPasswords",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        ApplicationId = c.Guid(nullable: false),
                        SaltedHashedPasswordWithAlgorithmAndSalt = c.String(),
                        CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.ApplicationPasswords");
        }
    }
}
