// <auto-generated />
namespace UBind.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPolicyInceptionAndExpiryDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPolicyInceptionAndExpiryDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201807200013465_Added policy inception and expiry dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
