// <auto-generated />
namespace UBind.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedReleaseAssetsAndDevReleases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedReleaseAssetsAndDevReleases));
        
        string IMigrationMetadata.Id
        {
            get { return "201905290715146_AddedReleaseAssetsAndDevReleases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
