// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class AddedReleaseAssetsAndDevReleases : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Assets",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    Name = c.String(),
                    Content = c.Binary(),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    ReleaseDetails_Id = c.Guid(),
                })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.ReleaseDetails", t => t.ReleaseDetails_Id)
                .Index(t => t.ReleaseDetails_Id);

            CreateTable(
                "dbo.DevReleases",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    TenantId = c.String(),
                    ProductId = c.String(),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                })
                .PrimaryKey(t => t.Id);

            AddColumn("dbo.ReleaseDescriptions", "DevRelease_Id", c => c.Guid());
            AddColumn("dbo.ReleaseEvents", "DevRelease_Id", c => c.Guid());
            CreateIndex("dbo.ReleaseDescriptions", "DevRelease_Id");
            CreateIndex("dbo.ReleaseEvents", "DevRelease_Id");
            AddForeignKey("dbo.ReleaseDescriptions", "DevRelease_Id", "dbo.DevReleases", "Id");
            AddForeignKey("dbo.ReleaseEvents", "DevRelease_Id", "dbo.DevReleases", "Id");
        }

        public override void Down()
        {
            DropForeignKey("dbo.ReleaseEvents", "DevRelease_Id", "dbo.DevReleases");
            DropForeignKey("dbo.ReleaseDescriptions", "DevRelease_Id", "dbo.DevReleases");
            DropForeignKey("dbo.Assets", "ReleaseDetails_Id", "dbo.ReleaseDetails");
            DropIndex("dbo.Assets", new[] { "ReleaseDetails_Id" });
            DropIndex("dbo.ReleaseEvents", new[] { "DevRelease_Id" });
            DropIndex("dbo.ReleaseDescriptions", new[] { "DevRelease_Id" });
            DropColumn("dbo.ReleaseEvents", "DevRelease_Id");
            DropColumn("dbo.ReleaseDescriptions", "DevRelease_Id");
            DropTable("dbo.DevReleases");
            DropTable("dbo.Assets");
        }
    }
}