// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddQuoteVersion : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.QuoteVersionReadModels",
                c => new
                    {
                        Id = c.String(nullable: false, maxLength: 128),
                        ProductId = c.String(),
                        Environment = c.Int(nullable: false),
                        QuoteId = c.Guid(nullable: false),
                        QuoteVersionNumber = c.Int(nullable: false),
                        LatestFormData = c.String(),
                        CustomerId = c.Guid(nullable: false),
                        CustomerPersonId = c.Guid(nullable: false),
                        CustomerFullName = c.String(),
                        CustomerPreferredName = c.String(),
                        CustomerEmail = c.String(),
                        CustomerAlternativeEmail = c.String(),
                        CustomerMobilePhone = c.String(),
                        CustomerHomePhone = c.String(),
                        CustomerWorkPhone = c.String(),
                        QuoteNumber = c.String(),
                        OwnerUserId = c.Guid(nullable: false),
                        OwnerPersonId = c.Guid(nullable: false),
                        OwnerFullName = c.String(),
                        CalculationResultJson = c.String(),
                        LastUpdatedTicksSinceEpoch = c.Long(nullable: false),
                        CreationTimeTicksSinceEpoch = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.QuoteVersionReadModels");
        }
    }
}
