// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedLoginAttemptResultandEmailBlockingEvententities : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.EmailBlockingEvents",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        TenantId = c.String(),
                        EmailAddress = c.String(),
                        IsAccountLocked = c.Boolean(nullable: false),
                        CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.LoginAttemptResults",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        TenantId = c.String(),
                        EmailAddress = c.String(),
                        Succeeded = c.Boolean(nullable: false),
                        ClientIpAddress = c.String(),
                        Error = c.String(),
                        CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.LoginAttemptResults");
            DropTable("dbo.EmailBlockingEvents");
        }
    }
}
