// <auto-generated />
namespace UBind.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSqlServerStorageForMiniProfiler : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSqlServerStorageForMiniProfiler));
        
        string IMigrationMetadata.Id
        {
            get { return "201908060259530_AddSqlServerStorageForMiniProfiler"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
