// <auto-generated />
namespace UBind.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreditNoteAndCreditNoteNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreditNoteAndCreditNoteNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202004140749553_CreditNoteAndCreditNoteNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
