// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
	using System.Data.Entity.Migrations;

	public partial class AddColumnLastUpdatedByUserTicksSinceEpoch : DbMigration
	{
        public override void Up()
        {
            AddColumn("dbo.Quotes", "LastUpdatedByUserTicksSinceEpoch", c => c.Long());
		}

		public override void Down()
		{
			DropColumn("dbo.Quotes", "LastUpdatedByUserTicksSinceEpoch");
		}
	}
}
