// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RenameDefaultRoles : DbMigration
    {
        public override void Up()
        {
            Sql("UPDATE dbo.Roles SET Name = 'Master Admin' WHERE Name = 'uBind admin'");
            Sql("UPDATE dbo.Roles SET Name = 'Tenant Admin' WHERE Name = 'Client admin'");
            Sql("UPDATE dbo.Roles SET Description = " +
                "'Full admin rights across the master tenancy' WHERE Name = 'Master Admin'");
            Sql("UPDATE dbo.Roles SET Description = " +
                "'Full admin rights across the tenancy' WHERE Name = 'Tenant Admin'");
            Sql("UPDATE dbo.Roles SET Description = " +
                "'Default role automatically assigned to customer users' WHERE Name = 'Customer'");
        }

        public override void Down()
        {
        }
    }
}
