// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddUserIdInTokenSession : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.TokenSessions", "UserId", c => c.Guid());
        }
        
        public override void Down()
        {
            DropColumn("dbo.TokenSessions", "UserId");
        }
    }
}
