// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedReportReadModelandReportFileentities : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.ReportReadModels",
                c => new
                    {
                        ReportId = c.Guid(nullable: false),
                        CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                        TenantId = c.String(),
                        Environment = c.Int(nullable: false),
                        Name = c.String(),
                        Description = c.String(),
                        SourceData = c.String(),
                        MimeType = c.String(),
                        Filename = c.String(),
                        Body = c.String(),
                        IsDeleted = c.Boolean(nullable: false),
                    })
                .PrimaryKey(t => t.ReportId);
            
            CreateTable(
                "dbo.ReportFiles",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Filename = c.String(),
                        Content = c.Binary(),
                        Size = c.Int(nullable: false),
                        ReportId = c.Guid(nullable: false),
                        CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.ReportProducts",
                c => new
                    {
                        ReportID = c.Guid(nullable: false),
                        ProductID = c.String(nullable: false, maxLength: 128),
                        TenantId = c.String(nullable: false, maxLength: 128),
                    })
                .PrimaryKey(t => new { t.ReportID, t.ProductID, t.TenantId })
                .ForeignKey("dbo.ReportReadModels", t => t.ReportID, cascadeDelete: true)
                .ForeignKey("dbo.Products", t => new { t.ProductID, t.TenantId }, cascadeDelete: true)
                .Index(t => t.ReportID)
                .Index(t => new { t.ProductID, t.TenantId });
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ReportProducts", new[] { "ProductID", "TenantId" }, "dbo.Products");
            DropForeignKey("dbo.ReportProducts", "ReportID", "dbo.ReportReadModels");
            DropIndex("dbo.ReportProducts", new[] { "ProductID", "TenantId" });
            DropIndex("dbo.ReportProducts", new[] { "ReportID" });
            DropTable("dbo.ReportProducts");
            DropTable("dbo.ReportFiles");
            DropTable("dbo.ReportReadModels");
        }
    }
}
