// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class AddQuoteExpirySettings : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.ProductDetails", "QuoteExpirySetting_Enabled", c => c.Boolean(nullable: false));
            AddColumn("dbo.ProductDetails", "QuoteExpirySetting_ExpiryDays", c => c.Int(nullable: false));
            AddColumn("dbo.Quotes", "ExpiryTimeAsTicksSinceEpoch", c => c.Long());
        }

        public override void Down()
        {
            DropColumn("dbo.Quotes", "ExpiryTimeAsTicksSinceEpoch");
            DropColumn("dbo.ProductDetails", "QuoteExpirySetting_ExpiryDays");
            DropColumn("dbo.ProductDetails", "QuoteExpirySetting_Enabled");
        }
    }
}
