// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddAutomationAndOutboundEmailToRelease : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.ReleaseDetails", "AutomationsJson", c => c.String());
            AddColumn("dbo.ReleaseDetails", "OutboundEmailServersJson", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.ReleaseDetails", "OutboundEmailServersJson");
            DropColumn("dbo.ReleaseDetails", "AutomationsJson");
        }
    }
}
