// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddPortalIdAndIsDeletedPropertyForQuoteAssociation : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.CustomerReadModels", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.SystemEmailTemplates", "PortalId", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.SystemEmailTemplates", "PortalId");
            DropColumn("dbo.CustomerReadModels", "IsDeleted");
        }
    }
}
