// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Helpers;

    public partial class PortalsPerOrganisation : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.SystemEmailTemplates", "PortalId", c => c.Guid());
            AlterColumn("dbo.UserReadModels", "CustomerId", c => c.Guid());
            AlterColumn("dbo.PersonReadModels", "CustomerId", c => c.Guid());
            AddColumn("dbo.CustomerReadModels", "PortalId", c => c.Guid());
            AddColumn("dbo.UserReadModels", "PortalId", c => c.Guid());
            AddColumn("dbo.Portals", "OrganisationId", c => c.Guid(nullable: false));
        }

        public override void Down()
        {
            Sql("Update dbo.PersonReadModels SET CustomerId = '00000000-0000-0000-0000-000000000000' WHERE "
                + "CustomerId IS NULL");
            Sql("Update dbo.UserReadModels SET CustomerId = '00000000-0000-0000-0000-000000000000' WHERE "
                + "CustomerId IS NULL");
            Sql("Update dbo.SystemEmailTemplates SET PortalId = '00000000-0000-0000-0000-000000000000' WHERE "
                + "PortalId IS NULL");

            DropColumn("dbo.Portals", "OrganisationId");
            DropColumn("dbo.UserReadModels", "PortalId");
            DropColumn("dbo.CustomerReadModels", "PortalId");
            AlterColumn("dbo.UserReadModels", "CustomerId", c => c.Guid(nullable: false));
            AlterColumn("dbo.PersonReadModels", "CustomerId", c => c.Guid(nullable: false));
            AlterColumn("dbo.SystemEmailTemplates", "PortalId", c => c.String());
        }
    }
}
