// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class AddPortalSettingsToTenantDetails : DbMigration
    {
        public override void Up()
        {
            this.AddColumnIfNotExists("dbo.TenantDetails", "DefaultPortalStylesheetUrl", c => c.String(nullable: true));
            this.AddColumnIfNotExists("dbo.TenantDetails", "DefaultPortalTitle", c => c.String(nullable: true));
        }

        public override void Down()
        {
            DropColumn("dbo.TenantDetails", "DefaultPortalTitle");
            DropColumn("dbo.TenantDetails", "DefaultPortalStylesheetUrl");
        }
    }
}
