// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CreateTable_ProductOrganisationSettings : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.ProductOrganisationSettings",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        TenantId = c.Guid(nullable: false),
                        OrganisationId = c.Guid(nullable: false),
                        ProductId = c.Guid(nullable: false),
                        IsNewQuotesAllowed = c.Boolean(nullable: false),
                        CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.ProductOrganisationSettings");
        }
    }
}
