// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class AddCustomDomainToTenantDetails : DbMigration
    {
        public override void Up()
        {
            this.AddColumnIfNotExists("dbo.TenantDetails", "CustomDomain", c => c.String());
        }

        public override void Down()
        {
            DropColumn("dbo.TenantDetails", "CustomDomain");
        }
    }
}
