// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class AddIsActualisedColumnsForQuotesAndClaimReadModels : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.ClaimReadModels", "IsActualised", c => c.Boolean(nullable: false));
            AddColumn("dbo.Quotes", "IsActualised", c => c.Boolean(nullable: false));
        }

        public override void Down()
        {
            DropColumn("dbo.Quotes", "IsActualised");
            DropColumn("dbo.ClaimReadModels", "IsActualised");
        }
    }
}
