// <auto-generated />

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class CreateTable_QuoteFileAttachments_And_PopulateFileContents : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.QuoteFileAttachments",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    QuoteId = c.Guid(nullable: false),
                    FileContentId = c.Guid(nullable: false),
                    Name = c.String(),
                    Type = c.String(),
                    FileSize = c.Long(nullable: false),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    Discriminator = c.String(nullable: false, maxLength: 128),
                })
                .PrimaryKey(t => t.Id);
        }

        public override void Down()
        {
            DropTable("dbo.QuoteFileAttachments");
        }
    }
}
