// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class AddQuoteTitleAndPolicyTitleColumns : DbMigration
    {
        public override void Up()
        {
            this.AddColumnIfNotExists("dbo.Quotes", "QuoteTitle", c => c.String());
            this.AddColumnIfNotExists("dbo.PolicyReadModels", "PolicyTitle", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.Quotes", "QuoteTitle");
            DropColumn("dbo.PolicyReadModels", "PolicyTitle");
        }
    }
}
