// <copyright file="202109021037143_CreateOrganisationAdminRole.cs" company="uBind">
// Copyright (c) uBind. All rights reserved.
// </copyright>

// If you edit this file, you must remove this line and then do proper null checking
#pragma warning disable CS8600, CS8625, CS8629, CS8618, CS8605, CS8604, CS8601, CS8602, CS8603, CS8622, CS8619, CS8767, CS8620, CS8765


// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Helpers;

    public partial class CreateOrganisationAdminRole : DbMigration
    {
        public override void Up()
        {
            var methodName = "CreateOrganisationAdminRoleForAllTenants_20210902";
            Sql(StartupJobRunnerQueryHelper.GenerateInsertQueryForStartupJobV1(methodName, true));
        }

        public override void Down()
        {
        }
    }
}
