// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class AllowRenewalAfterExpiry : DbMigration
    {
        public override void Up()
        {
            this.AddColumnIfNotExists("dbo.ProductFeatureSettings", "IsRenewalAllowedAfterExpiry", c => c.Boolean(nullable: false));
            this.AddColumnIfNotExists("dbo.ProductFeatureSettings", "ExpiredPolicyRenewalDurationInSeconds", c => c.Int(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.ProductFeatureSettings", "ExpiredPolicyRenewalDurationInSeconds");
            DropColumn("dbo.ProductFeatureSettings", "IsRenewalAllowedAfterExpiry");
        }
    }
}
