// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class AddedOrganisationUserChangesFeature : DbMigration
    {
        public override void Up()
        {
            DropIndex("dbo.UserLoginEmails", "AK_UserTenantAndEmailIndex");
            this.AddColumnIfNotExists("dbo.EmailAddressBlockingEvents", "OrganisationId", c => c.Guid(nullable: false));
            this.AddColumnIfNotExists("dbo.LoginAttemptResults", "OrganisationId", c => c.Guid(nullable: false));
            this.AddColumnIfNotExists("dbo.PasswordResetRecords", "OrganisationId", c => c.Guid(nullable: false));
            this.AddColumnIfNotExists("dbo.Roles", "OrganisationId", c => c.Guid(nullable: false));
            this.AddColumnIfNotExists("dbo.TokenSessions", "OrganisationId", c => c.Guid(nullable: false));
            this.AddColumnIfNotExists("dbo.UserLoginEmails", "OrganisationId", c => c.Guid(nullable: false));
            this.CreateIndexDropFirstIfExists("dbo.UserLoginEmails", new[] { "TenantId", "LoginEmail", "OrganisationId" }, unique: true, name: "AK_UserTenantOrganisationAndEmailIndex");
        }
        
        public override void Down()
        {
            DropIndex("dbo.UserLoginEmails", "AK_UserTenantOrganisationAndEmailIndex");
            DropColumn("dbo.UserLoginEmails", "OrganisationId");
            DropColumn("dbo.TokenSessions", "OrganisationId");
            DropColumn("dbo.Roles", "OrganisationId");
            DropColumn("dbo.PasswordResetRecords", "OrganisationId");
            DropColumn("dbo.LoginAttemptResults", "OrganisationId");
            DropColumn("dbo.EmailAddressBlockingEvents", "OrganisationId");
            this.CreateIndexDropFirstIfExists("dbo.UserLoginEmails", new[] { "TenantId", "LoginEmail" }, unique: true, name: "AK_UserTenantAndEmailIndex");
        }
    }
}
