// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class AddPolicyRelatedDetailsOnQuotesTable : DbMigration
    {
        public override void Up()
        {
            this.AddColumnIfNotExists("dbo.Quotes", "CustomerPersonId", c => c.Guid());
            this.AddColumnIfNotExists("dbo.Quotes", "CustomerFullName", c => c.String());
            this.AddColumnIfNotExists("dbo.Quotes", "CustomerPreferredName", c => c.String());
            this.AddColumnIfNotExists("dbo.Quotes", "CustomerEmail", c => c.String());
            this.AddColumnIfNotExists("dbo.Quotes", "CustomerAlternativeEmail", c => c.String());
            this.AddColumnIfNotExists("dbo.Quotes", "CustomerMobilePhone", c => c.String());
            this.AddColumnIfNotExists("dbo.Quotes", "CustomerHomePhone", c => c.String());
            this.AddColumnIfNotExists("dbo.Quotes", "CustomerWorkPhone", c => c.String());
            this.AddColumnIfNotExists("dbo.Quotes", "OwnerPersonId", c => c.Guid());
            this.AddColumnIfNotExists("dbo.Quotes", "OwnerFullName", c => c.String());
            this.AddColumnIfNotExists("dbo.Quotes", "PolicyNumber", c => c.String());
            this.AddColumnIfNotExists("dbo.Quotes", "AggregateId", c => c.Guid(nullable: false));

            AlterColumn("dbo.PolicyReadModels", "OwnerUserId", c => c.Guid());
            AlterColumn("dbo.PolicyReadModels", "OwnerPersonId", c => c.Guid());
            AlterColumn("dbo.PolicyTransactions", "OwnerUserId", c => c.Guid());
            AlterColumn("dbo.Quotes", "OwnerUserId", c => c.Guid());
            AlterColumn("dbo.Quotes", "PolicyId", c => c.Guid());
            AlterColumn("dbo.QuoteVersionReadModels", "OwnerUserId", c => c.Guid());
            AlterColumn("dbo.QuoteVersionReadModels", "OwnerPersonId", c => c.Guid());

            Sql
            (
                @"UPDATE Q 
                    SET 
                      Q.CustomerPersonId = C.PersonId,
                      Q.CustomerFullName = C.FullName, 
                      Q.CustomerPreferredName = C.PreferredName, 
                      Q.CustomerEmail = C.Email, 
                      Q.CustomerAlternativeEmail = C.AlternativeEmail, 
                      Q.CustomerMobilePhone = C.MobilePhoneNumber, 
                      Q.CustomerHomePhone = C.HomePhoneNumber, 
                      Q.CustomerWorkPhone = C.WorkPhoneNumber
                FROM dbo.Quotes Q
                INNER JOIN dbo.CustomerReadModels C ON Q.CustomerId = C.Id"
            );

            Sql
            (
                @"UPDATE Q 
                    SET 
                      Q.OwnerPersonId = U.PersonId, 
                      Q.OwnerFullName = U.FullName 
                FROM dbo.Quotes Q
                INNER JOIN dbo.UserReadModels U ON Q.OwnerUserId = U.UserId"
            );

            Sql
            (
                @"UPDATE Q 
                              SET 
                                  Q.AggregateId = Q.PolicyId 
                              FROM dbo.Quotes Q"
            );

            Sql
            (
                @"UPDATE Q 
                  SET 
                      Q.PolicyNumber = P.PolicyNumber 
                  FROM dbo.Quotes Q
                  INNER JOIN dbo.PolicyReadModels P ON Q.PolicyId = P.Id"
            );
        }

        public override void Down()
        {
            DropColumn("dbo.Quotes", "OwnerFullName");
            DropColumn("dbo.Quotes", "OwnerPersonId");
            DropColumn("dbo.Quotes", "CustomerWorkPhone");
            DropColumn("dbo.Quotes", "CustomerHomePhone");
            DropColumn("dbo.Quotes", "CustomerMobilePhone");
            DropColumn("dbo.Quotes", "CustomerAlternativeEmail");
            DropColumn("dbo.Quotes", "CustomerEmail");
            DropColumn("dbo.Quotes", "CustomerPreferredName");
            DropColumn("dbo.Quotes", "CustomerFullName");
            DropColumn("dbo.Quotes", "CustomerPersonId");
            DropColumn("dbo.Quotes", "AggregateId");
            DropColumn("dbo.Quotes", "PolicyNumber");

            AlterColumn("dbo.QuoteVersionReadModels", "OwnerPersonId", c => c.Guid(nullable: false));
            AlterColumn("dbo.QuoteVersionReadModels", "OwnerUserId", c => c.Guid(nullable: false));
            AlterColumn("dbo.Quotes", "OwnerPersonId", c => c.Guid(nullable: false));
            AlterColumn("dbo.Quotes", "OwnerUserId", c => c.Guid(nullable: false));
            AlterColumn("dbo.Quotes", "CustomerPersonId", c => c.Guid(nullable: false));
            AlterColumn("dbo.PolicyTransactions", "OwnerUserId", c => c.Guid(nullable: false));
            AlterColumn("dbo.PolicyReadModels", "OwnerPersonId", c => c.Guid(nullable: false));
            AlterColumn("dbo.PolicyReadModels", "OwnerUserId", c => c.Guid(nullable: false));
        }
    }
}
