// <auto-generated />

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class FileContent_AddColumn_HashCode : DbMigration
    {
        public override void Up()
        {
            this.AddColumnIfNotExists("dbo.FileContents", "HashCode", c => c.String(maxLength: 128));

            // Create index on HashCode column
            this.CreateIndexDropFirstIfExists(
                "dbo.FileContents", new[] { "HashCode" }, false, "IX_FileContents_HashCode");
        }

        public override void Down()
        {
            DropColumn("dbo.FileContents", "HashCode");
        }
    }
}
