// <auto-generated />

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Helpers;

    public partial class AddStartupJob_InitialDataSeederMigration : DbMigration
    {
        private readonly string alias = "InitialDataSeeder";

        public override void Up()
        {
            this.Sql(StartupJobRunnerQueryHelper.GenerateInsertQueryForStartupJobV1(this.alias));
        }

        public override void Down()
        {
            this.Sql(StartupJobRunnerQueryHelper.GenerateDeleteQueryForStartupJob(this.alias));
        }
    }
}
