// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class AddPaymentColumnsOnQuoteReadModel : DbMigration
    {
        public override void Up()
        {
            // expected values are deft, stripe, eway
            this.AddColumnIfNotExists("dbo.Quotes", "PaymentGateway", c => c.String(maxLength: 20, nullable: true));

            //expected value is json string of PaymentMadeEvent class
            this.AddColumnIfNotExists("dbo.Quotes", "PaymentResponseJson", c => c.String(nullable: true));
        }
        
        public override void Down()
        {
            DropColumn("dbo.Quotes", "PaymentGateway");
            DropColumn("dbo.Quotes", "PaymentResponseJson");
        }
    }
}
