// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddLastModifiedToOrganisationEntity : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.OrganisationReadModels", "LastModifiedTicksSinceEpoch", c => c.Long(nullable: false, defaultValue: DateTime.Now.Ticks));
            Sql("UPDATE dbo.OrganisationReadModels SET LastModifiedTicksSinceEpoch = CreationTimeInTicksSinceEpoch");
        }
        
        public override void Down()
        {
            DropColumn("dbo.OrganisationReadModels", "LastModifiedTicksSinceEpoch");
        }
    }
}
