// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class MakeCustomerOptionalForQuotesAndClaims : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.ClaimReadModels", "CustomerId", c => c.Guid());
            AlterColumn("dbo.ClaimReadModels", "PersonId", c => c.Guid());
            AlterColumn("dbo.ClaimVersionReadModels", "CustomerId", c => c.Guid());
            AlterColumn("dbo.PolicyReadModels", "CustomerId", c => c.Guid());
            AlterColumn("dbo.PolicyReadModels", "CustomerPersonId", c => c.Guid());
            AlterColumn("dbo.PolicyTransactions", "CustomerId", c => c.Guid());
            AlterColumn("dbo.QuoteDocumentReadModels", "CustomerId", c => c.Guid());
            AlterColumn("dbo.Quotes", "CustomerId", c => c.Guid());
            AlterColumn("dbo.QuoteVersionReadModels", "CustomerId", c => c.Guid());
            AlterColumn("dbo.QuoteVersionReadModels", "CustomerPersonId", c => c.Guid());
        }

        public override void Down()
        {
            Sql("Update dbo.ClaimReadModels SET CustomerId = '00000000-0000-0000-0000-000000000000' WHERE CustomerId IS NULL");
            Sql("Update dbo.ClaimReadModels SET PersonId = '00000000-0000-0000-0000-000000000000' WHERE PersonId IS NULL");
            Sql("Update dbo.ClaimVersionReadModels SET CustomerId = '00000000-0000-0000-0000-000000000000' WHERE CustomerId IS NULL");
            Sql("Update dbo.PolicyReadModels SET CustomerId = '00000000-0000-0000-0000-000000000000' WHERE CustomerId IS NULL");
            Sql("Update dbo.PolicyReadModels SET CustomerPersonId = '00000000-0000-0000-0000-000000000000' WHERE CustomerPersonId IS NULL");
            Sql("Update dbo.PolicyTransactions SET CustomerId = '00000000-0000-0000-0000-000000000000' WHERE CustomerId IS NULL");
            Sql("Update dbo.QuoteDocumentReadModels SET CustomerId = '00000000-0000-0000-0000-000000000000' WHERE CustomerId IS NULL");
            Sql("Update dbo.Quotes SET CustomerId = '00000000-0000-0000-0000-000000000000' WHERE CustomerId IS NULL");
            Sql("Update dbo.QuoteVersionReadModels SET CustomerId = '00000000-0000-0000-0000-000000000000' WHERE CustomerId IS NULL");
            Sql("Update dbo.QuoteVersionReadModels SET CustomerPersonId = '00000000-0000-0000-0000-000000000000' WHERE CustomerPersonId IS NULL");

            AlterColumn("dbo.QuoteVersionReadModels", "CustomerPersonId", c => c.Guid(nullable: false));
            AlterColumn("dbo.QuoteVersionReadModels", "CustomerId", c => c.Guid(nullable: false));
            AlterColumn("dbo.Quotes", "CustomerId", c => c.Guid(nullable: false));
            AlterColumn("dbo.QuoteDocumentReadModels", "CustomerId", c => c.Guid(nullable: false));
            AlterColumn("dbo.PolicyTransactions", "CustomerId", c => c.Guid(nullable: false));
            AlterColumn("dbo.PolicyReadModels", "CustomerPersonId", c => c.Guid(nullable: false));
            AlterColumn("dbo.PolicyReadModels", "CustomerId", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClaimVersionReadModels", "CustomerId", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClaimReadModels", "PersonId", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClaimReadModels", "CustomerId", c => c.Guid(nullable: false));
        }
    }
}
