// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Helpers;

    public partial class AddedPersonReadModelAndStartUpJobs : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.PersonReadModels",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    PersonId = c.Guid(nullable: false),
                    Environment = c.Int(nullable: false),
                    UserId = c.Guid(nullable: false),
                    IsTestData = c.Boolean(nullable: false),
                    CustomerId = c.Guid(nullable: false),
                    UserHasBeenInvitedToActivate = c.Boolean(nullable: false),
                    UserHasBeenActivated = c.Boolean(nullable: false),
                    UserIsBlocked = c.Boolean(nullable: false),
                    IsDeleted = c.Boolean(nullable: false),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    FullName = c.String(),
                    NamePrefix = c.String(),
                    FirstName = c.String(),
                    MiddleNames = c.String(),
                    LastName = c.String(),
                    NameSuffix = c.String(),
                    Company = c.String(),
                    Title = c.String(),
                    PreferredName = c.String(),
                    Email = c.String(),
                    AlternativeEmail = c.String(),
                    MobilePhoneNumber = c.String(),
                    HomePhoneNumber = c.String(),
                    WorkPhoneNumber = c.String(),
                    TenantId = c.String(),
                    OrganisationId = c.Guid(nullable: false),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.StartupJobs",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    Alias = c.String(),
                    Complete = c.Boolean(nullable: false),
                    Blocking = c.Boolean(nullable: false),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                })
                .PrimaryKey(t => t.Id);


            var methodName = "RegeneratePersonReadModels";
            Sql(StartupJobRunnerQueryHelper.GenerateInsertQueryForStartupJobV1(methodName));
        }

        public override void Down()
        {
            DropTable("dbo.StartupJobs");
            DropTable("dbo.PersonReadModels");
        }
    }
}
