// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class AddIndexingForRelationshipsAndTags : DbMigration
    {
        public override void Up()
        {
            this.CreateIndexDropFirstIfExists("dbo.Relationships", new[] { "Type", "FromEntityType", "FromEntityId" }, name: "AK_RelationshipFromTypeIndex");
            this.CreateIndexDropFirstIfExists("dbo.Relationships", new[] { "FromEntityId" }, name: "AK_RelationshipFromEntityIndex");
            this.CreateIndexDropFirstIfExists("dbo.Relationships", new[] { "Type", "ToEntityType", "ToEntityId" }, name: "AK_RelationshipToTypeIndex");
            this.CreateIndexDropFirstIfExists("dbo.Relationships", new[] { "ToEntityId" }, name: "AK_RelationshipToEntityIndex");
            this.CreateIndexDropFirstIfExists("dbo.Tags", new[] { "EntityId" }, name: "AK_TagEntityIndex");
            this.CreateIndexDropFirstIfExists("dbo.Tags", new[] { "TagType", "EntityType", "EntityId" }, name: "AK_TagEntityTypeIndex");
        }

        public override void Down()
        {
            DropIndex("dbo.Tags", "AK_TagEntityTypeIndex");
            DropIndex("dbo.Tags", "AK_TagEntityIndex");
            DropIndex("dbo.Relationships", "AK_RelationshipToEntityIndex");
            DropIndex("dbo.Relationships", "AK_RelationshipToTypeIndex");
            DropIndex("dbo.Relationships", "AK_RelationshipFromEntityIndex");
            DropIndex("dbo.Relationships", "AK_RelationshipFromTypeIndex");
        }
    }
}
