// <auto-generated />



#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    using System.IO;
    using UBind.Persistence.Migrations.Extensions;

    public partial class AddProfilePictureIdColumnToUserReadModel : DbMigration
    {
        public override void Up()
        {
            this.AddColumnIfNotExists("dbo.UserReadModels", "ProfilePictureId", c => c.Guid(nullable: true));

            var sqlFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Migrations", @"202104220824459_AddProfilePictureIdColumnToUserReadModel.sql");
            this.Sql(File.ReadAllText(sqlFile));
        }

        public override void Down()
        {
            DropColumn("dbo.UserReadModels", "ProfilePictureId");
        }
    }
}
