// <auto-generated />
namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedAdditionalPropertyDefinitionAndTexAdditionalPropertyValueTables : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.AdditionalPropertyDefinitions",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Alias = c.String(),
                        Name = c.String(),
                        EntityType = c.Int(nullable: false),
                        ContextType = c.Int(nullable: false),
                        ContextId = c.String(),
                        IsRequired = c.Boolean(nullable: false),
                        IsUnique = c.Boolean(nullable: false),
                        IsDeleted = c.Boolean(nullable: false),
                        ParentContextId = c.String(),
                        DefaultValue = c.String(),
                        PropertyType = c.Int(nullable: false),
                        LastUpdatedTicksSinceEpoch = c.Long(nullable: false),
                        TenantNewId = c.Guid(nullable: false),
                        CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id);
            
            CreateTable(
                "dbo.TextAdditionalPropertyValueReadModels",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        AdditionalPropertyDefinitionId = c.Guid(nullable: false),
                        Value = c.String(),
                        EntityId = c.String(),
                        TenantNewId = c.Guid(nullable: false),
                        CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.AdditionalPropertyDefinitions", t => t.AdditionalPropertyDefinitionId, cascadeDelete: true)
                .Index(t => t.AdditionalPropertyDefinitionId);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.TextAdditionalPropertyValueReadModels", "AdditionalPropertyDefinitionId", "dbo.AdditionalPropertyDefinitions");
            DropIndex("dbo.TextAdditionalPropertyValueReadModels", new[] { "AdditionalPropertyDefinitionId" });
            DropTable("dbo.TextAdditionalPropertyValueReadModels");
            DropTable("dbo.AdditionalPropertyDefinitions");
        }
    }
}
