// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class RemoveApplicationEntity : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.CalculationResults", "Application_Id", "dbo.Applications");
            DropForeignKey("dbo.CustomerDetails", "Application_Id", "dbo.Applications");
            DropForeignKey("dbo.ApplicationFileAttachments", "Application_Id", "dbo.Applications");
            DropForeignKey("dbo.FormDatas", "Application_Id", "dbo.Applications");
            DropForeignKey("dbo.Applications", "Invoice_Id", "dbo.InvoiceObsoletes");
            DropForeignKey("dbo.Ownerships", "ApplicationId", "dbo.Applications");
            DropForeignKey("dbo.PaymentAttemptResults", "Application_Id", "dbo.Applications");
            DropForeignKey("dbo.Applications", "Policy_Id", "dbo.Policies");
            DropForeignKey("dbo.QuoteNumbers", "Id", "dbo.Applications");
            DropForeignKey("dbo.Applications", "Submission_Id", "dbo.ApplicationSubmissions");
            DropIndex("dbo.Applications", new[] { "Invoice_Id" });
            DropIndex("dbo.Applications", new[] { "Policy_Id" });
            DropIndex("dbo.Applications", new[] { "Submission_Id" });
            DropIndex("dbo.CalculationResults", new[] { "Application_Id" });
            DropIndex("dbo.CustomerDetails", new[] { "Application_Id" });
            DropIndex("dbo.ApplicationFileAttachments", new[] { "Application_Id" });
            DropIndex("dbo.FormDatas", new[] { "Application_Id" });
            DropIndex("dbo.Ownerships", new[] { "ApplicationId" });
            DropIndex("dbo.PaymentAttemptResults", new[] { "Application_Id" });
            DropIndex("dbo.QuoteNumbers", new[] { "Id" });
            DropTable("dbo.CalculationResults");
            DropTable("dbo.CustomerDetails");
            DropTable("dbo.ApplicationFileAttachments");
            DropTable("dbo.FormDatas");
            DropTable("dbo.InvoiceObsoletes");
            DropTable("dbo.Ownerships");
            DropTable("dbo.PaymentAttemptResults");
            DropTable("dbo.Policies");
            DropTable("dbo.QuoteNumbers");
            DropTable("dbo.ApplicationSubmissions");
            DropTable("dbo.Applications");
        }

        public override void Down()
        {
            CreateTable(
                "dbo.ApplicationSubmissions",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    SubmittedFormUpdateId = c.Guid(nullable: false),
                    SubmittedCalculationResultId = c.Guid(nullable: false),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.QuoteNumbers",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    ProductId = c.String(),
                    Environment = c.Int(nullable: false),
                    Method = c.Int(nullable: false),
                    Number = c.String(),
                    Seed = c.Int(),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.Policies",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    PolicyNumber = c.String(),
                    InceptionDate = c.String(),
                    CancellationDate = c.String(),
                    ExpiryDate = c.String(),
                    SubmittedCustomerDetailsId = c.Guid(nullable: false),
                    SubmittedFormUpdateId = c.Guid(nullable: false),
                    SubmittedCalculationResultId = c.Guid(nullable: false),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.PaymentAttemptResults",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    Reference = c.String(),
                    Outcome = c.Int(nullable: false),
                    SubmittedFormUpdateId = c.Guid(nullable: false),
                    SubmittedCalculationResultId = c.Guid(nullable: false),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    Application_Id = c.Guid(),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.Ownerships",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    OwnerId = c.Guid(nullable: false),
                    ApplicationId = c.Guid(nullable: false),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.InvoiceObsoletes",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    InvoiceNumber = c.String(),
                    SubmittedFormUpdateId = c.Guid(nullable: false),
                    SubmittedCalculationResultId = c.Guid(nullable: false),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.FormDatas",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    Json = c.String(),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    Application_Id = c.Guid(),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.ApplicationFileAttachments",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    Name = c.String(),
                    Type = c.String(),
                    Content = c.String(),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    Application_Id = c.Guid(),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.CustomerDetails",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    Name = c.String(),
                    PhoneNumber = c.String(),
                    Email = c.String(),
                    MobileNumber = c.String(),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    Application_Id = c.Guid(),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.CalculationResults",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    FormDataId = c.Guid(nullable: false),
                    Json = c.String(),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    Application_Id = c.Guid(),
                })
                .PrimaryKey(t => t.Id);

            CreateTable(
                "dbo.Applications",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    ProductId = c.String(),
                    ProductNewId = c.Guid(nullable: false),
                    Environment = c.Int(nullable: false),
                    CreationTimeInTicksSinceEpoch = c.Long(nullable: false),
                    Invoice_Id = c.Guid(),
                    Policy_Id = c.Guid(),
                    Submission_Id = c.Guid(),
                })
                .PrimaryKey(t => t.Id);

            CreateIndex("dbo.QuoteNumbers", "Id");
            CreateIndex("dbo.PaymentAttemptResults", "Application_Id");
            CreateIndex("dbo.Ownerships", "ApplicationId");
            CreateIndex("dbo.FormDatas", "Application_Id");
            CreateIndex("dbo.ApplicationFileAttachments", "Application_Id");
            CreateIndex("dbo.CustomerDetails", "Application_Id");
            CreateIndex("dbo.CalculationResults", "Application_Id");
            CreateIndex("dbo.Applications", "Submission_Id");
            CreateIndex("dbo.Applications", "Policy_Id");
            CreateIndex("dbo.Applications", "Invoice_Id");
            AddForeignKey("dbo.Applications", "Submission_Id", "dbo.ApplicationSubmissions", "Id");
            AddForeignKey("dbo.QuoteNumbers", "Id", "dbo.Applications", "Id");
            AddForeignKey("dbo.Applications", "Policy_Id", "dbo.Policies", "Id");
            AddForeignKey("dbo.PaymentAttemptResults", "Application_Id", "dbo.Applications", "Id");
            AddForeignKey("dbo.Ownerships", "ApplicationId", "dbo.Applications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Applications", "Invoice_Id", "dbo.InvoiceObsoletes", "Id");
            AddForeignKey("dbo.FormDatas", "Application_Id", "dbo.Applications", "Id");
            AddForeignKey("dbo.ApplicationFileAttachments", "Application_Id", "dbo.Applications", "Id");
            AddForeignKey("dbo.CustomerDetails", "Application_Id", "dbo.Applications", "Id");
            AddForeignKey("dbo.CalculationResults", "Application_Id", "dbo.Applications", "Id");
        }
    }
}
