// <auto-generated />
namespace UBind.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SmsRelationshipEmailAndPersonRelatedEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SmsRelationshipEmailAndPersonRelatedEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "202206280414078_SmsRelationshipEmailAndPersonRelatedEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
