// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Helpers;

    public partial class FixAssociationAndUserTypeForImportedCustomers : DbMigration
    {
        private string startupJobAlias = "FixPersonRecordAssociationAndUserTypeForImportedCustomers_170822";
        public override void Up()
        {
            this.Sql(StartupJobRunnerQueryHelper.GenerateInsertQueryForStartupJobV1(this.startupJobAlias, runManuallyIfInMultiNode: true));

        }

        public override void Down()
        {
            this.Sql(StartupJobRunnerQueryHelper.GenerateDeleteQueryForStartupJob(this.startupJobAlias));
        }
    }
}
