// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class UpdateMidTermAdjustmentTransactionToAdustmentTransaction : DbMigration
    {
        public override void Up()
        {
            this.Sql("update [dbo].[PolicyTransactions] set [Discriminator] = 'AdjustmentTransaction' where [Discriminator] = 'MidTermAdjustmentTransaction';");
        }
        
        public override void Down()
        {
            this.Sql("update [dbo].[PolicyTransactions] set [Discriminator] = 'MidTermAdjustmentTransaction' where [Discriminator] = 'AdjustmentTransaction';");
        }
    }
}
