// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Helpers;

    public partial class AddTenantIdInEventTable : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.EventRecordWithGuidIds", "TenantId", c => c.Guid(defaultValue: default));
            AddColumn("dbo.EventRecordWithStringIds", "TenantId", c => c.Guid());
            var createStartupJobRecord = StartupJobRunnerQueryHelper.GenerateInsertQueryForStartupJobV1(
                "AddTenantIdToPersonRelatedEvents_20220120803395",
                false,
                true);
            Sql(createStartupJobRecord);
        }
        
        public override void Down()
        {
            DropColumn("dbo.EventRecordWithStringIds", "TenantId");
            DropColumn("dbo.EventRecordWithGuidIds", "TenantId");
            StartupJobRunnerQueryHelper.GenerateDeleteQueryForStartupJob("AddTenantIdToPersonRelatedEvents_20220120803395");
        }
    }
}
