// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class RefundSettings : DbMigration
    {
        public override void Up()
        {
            this.AddColumnIfNotExists("dbo.ProductFeatureSettings", "RefundRule", c => c.Int(nullable: false, defaultValue : 0));
            this.AddColumnIfNotExists("dbo.ProductFeatureSettings", "PeriodOfNoClaimsToQualifyForRefund", c => c.Int());
            this.AddColumnIfNotExists("dbo.ProductFeatureSettings", "LastNumberOfYearsOfNoClaimsToQualifyForRefund", c => c.Int());
        }

        public override void Down()
        {
            DropColumn("dbo.ProductFeatureSettings", "LastNumberOfYearsOfNoClaimsToQualifyForRefund");
            DropColumn("dbo.ProductFeatureSettings", "PeriodOfNoClaimsToQualifyForRefund");
            DropColumn("dbo.ProductFeatureSettings", "RefundRule");
        }
    }
}
