// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Helpers;
    using UBind.Persistence.Migrations.Extensions;

    public partial class CreateEnvironmentColumnForEmail : DbMigration
    {
        private string fillEnvironmentForEmail = "FillEnvironmentColumnForEmail_20221028";

        public override void Up()
        {
            this.AddColumnIfNotExists("dbo.Emails", "Environment", c => c.Int());
            this.AddColumnIfNotExists("dbo.Emails", "HasAttachments", c => c.Boolean(nullable: false));

            this.Sql(StartupJobRunnerQueryHelper.GenerateInsertQueryForStartupJob(
             this.fillEnvironmentForEmail, false, false));
        }

        public override void Down()
        {
            DropColumn("dbo.Emails", "HasAttachments");
            DropColumn("dbo.Emails", "Environment");

            this.Sql(
                StartupJobRunnerQueryHelper.GenerateDeleteQueryForStartupJob(
                this.fillEnvironmentForEmail));
        }
    }
}