// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class ResizeLoginAttemptResultsEmailAddress : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.LoginAttemptResults", "EmailAddress", c => c.String(maxLength: 320));
            AlterColumn("dbo.PasswordResetRecords", "EmailAddress", c => c.String(maxLength: 320));
        }

        public override void Down()
        {
            AlterColumn("dbo.PasswordResetRecords", "EmailAddress", c => c.String());
            AlterColumn("dbo.LoginAttemptResults", "EmailAddress", c => c.String());
        }
    }
}
