// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Helpers;

    public partial class FixNullAggregate : DbMigration
    {
        string startupJobName = "FixNullQuoteAggregateFromPolicy_20220102";

        public override void Up()
        {
            var createStartupJobRecord = StartupJobRunnerQueryHelper.GenerateInsertQueryForStartupJobV1(
               startupJobName,
               false,
               true);
            this.Sql(createStartupJobRecord);
        }

        public override void Down()
        {
            var createStartupJobRecord = StartupJobRunnerQueryHelper.GenerateDeleteQueryForStartupJob(
                  startupJobName);
            this.Sql(createStartupJobRecord);
        }
    }
}
