// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations;

using System.Data.Entity.Migrations;
using UBind.Persistence.Helpers;
using UBind.Persistence.Migrations.Extensions;

public partial class CombinedMigrationForRelease11_1 : DbMigration
{
    string startupJobName = "UpdatePolicyExpiryDate_202306160025592";

    public override void Up()
    {
        // this is the cause of the error. was just AddColumn()
        this.AddColumnIfNotExists("dbo.ReleaseDetails", "PaymentFormJson", c => c.String());

        this.Sql(StartupJobRunnerQueryHelper.GenerateInsertQueryForStartupJob(startupJobName));

        this.AddColumnIfNotExists("dbo.Settings", "IconLibrary", c => c.Int());
        this.Sql("UPDATE dbo.Settings set IconLibrary=0");
        this.Sql("UPDATE dbo.Settings set IconLibrary=2 WHERE Id='quote-mgmt'");
        this.Sql("UPDATE dbo.Settings set Icon='person', IconLibrary=1 WHERE Id='customer-mgmt'");
        this.Sql("UPDATE dbo.Settings set Icon='contact', IconLibrary=0 WHERE Id='user-mgmt'");
        this.Sql("UPDATE dbo.Settings set Icon='shield', IconLibrary=2 WHERE Id='policy-mgmt'");
        this.Sql("UPDATE dbo.Settings set Icon='clipboard', IconLibrary=2 WHERE Id='claims-mgmt'");
    }

    public override void Down()
    {
        DropColumn("dbo.ReleaseDetails", "PaymentFormJson");

        this.Sql(StartupJobRunnerQueryHelper.GenerateDeleteQueryForStartupJob(startupJobName));

        this.DropColumnIfExists("dbo.Settings", "IconLibrary");
        this.Sql("UPDATE dbo.Settings set Icon='contact' WHERE Id='customer-mgmt'");
        this.Sql("UPDATE dbo.Settings set Icon='people' WHERE Id='user-mgmt'");
        this.Sql("UPDATE dbo.Settings set Icon='ribbon' WHERE Id='policy-mgmt'");
        this.Sql("UPDATE dbo.Settings set Icon='alert' WHERE Id='claims-mgmt'");
    }
}
