// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Helpers;

    public partial class AddManagePolicyClaimNumbersToClientRoles : DbMigration
    {
        private const string AddManagePolicyClaimNumberToClientRolesMethodName = "AddManagePolicyNumberAndManageClaimNumbersToClientRoles_20231118";

        public override void Up()
        {
            this.Sql(StartupJobRunnerQueryHelper
                .GenerateInsertQueryForStartupJob(AddManagePolicyClaimNumberToClientRolesMethodName, runManuallyIfInMultiNode: true));
        }

        public override void Down()
        {
            this.Sql(StartupJobRunnerQueryHelper
                .GenerateDeleteQueryForStartupJob(AddManagePolicyClaimNumberToClientRolesMethodName));
        }
    }
}
