// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class AdditionalPropertyDefinitionWithStructuredDataValueTable : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.StructuredDataAdditionalPropertyValueReadModels",
                c => new
                {
                    Id = c.Guid(nullable: false),
                    AdditionalPropertyDefinitionId = c.Guid(nullable: false),
                    Value = c.String(),
                    EntityId = c.Guid(nullable: false),
                    TenantId = c.Guid(nullable: false),
                    CreatedTicksSinceEpoch = c.Long(nullable: false),
                })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.AdditionalPropertyDefinitions", t => t.AdditionalPropertyDefinitionId, cascadeDelete: true)
                .Index(t => t.AdditionalPropertyDefinitionId);

            AddColumn("dbo.AdditionalPropertyDefinitions", "SchemaType", c => c.Int());
            AddColumn("dbo.AdditionalPropertyDefinitions", "CustomSchema", c => c.String());
        }

        public override void Down()
        {
            DropForeignKey("dbo.StructuredDataAdditionalPropertyValueReadModels", "AdditionalPropertyDefinitionId", "dbo.AdditionalPropertyDefinitions");
            DropIndex("dbo.StructuredDataAdditionalPropertyValueReadModels", new[] { "AdditionalPropertyDefinitionId" });
            DropColumn("dbo.AdditionalPropertyDefinitions", "CustomSchema");
            DropColumn("dbo.AdditionalPropertyDefinitions", "SchemaType");
            DropTable("dbo.StructuredDataAdditionalPropertyValueReadModels");
        }
    }
}