// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class CreateIndexForFasterReports : DbMigration
    {
        public override void Up()
        {
            this.CreateIndexDropFirstIfExists("dbo.PolicyReadModels", new[] { "TenantId", "ProductId", "Environment" }, name: "IX_Policies_TenantId_ProductId_Environment");
            this.CreateIndexDropFirstIfExists("dbo.PolicyReadModels", new[] { "QuoteId" }, name: "IX_Policies_QuoteId");
            this.CreateIndexDropFirstIfExists("dbo.PolicyReadModels", new[] { "OrganisationId" }, name: "IX_Policies_OrganisationId");
            this.CreateIndexDropFirstIfExists("dbo.Products", new[] { "TenantId" }, name: "IX_Products_TenantId");
            this.CreateIndexDropFirstIfExists("dbo.PolicyTransactions", new[] { "CreatedTicksSinceEpoch" }, name: "IX_PolicyTransactions_CreatedTicksSinceEpoch");
            this.CreateIndexDropFirstIfExists("dbo.PolicyTransactions", new[] { "PolicyId" }, name: "IX_PolicyTransactions_PolicyId");
        }

        public override void Down()
        {
            DropIndex("dbo.Products", "IX_Products_TenantId");
            DropIndex("dbo.PolicyReadModels", "IX_Policies_OrganisationId");
            DropIndex("dbo.PolicyReadModels", "IX_Policies_QuoteId");
            DropIndex("dbo.PolicyReadModels", "IX_Policies_TenantId_ProductId_Environment");
            DropIndex("dbo.PolicyTransactions", "IX_PolicyTransactions_CreatedTicksSinceEpoch");
            DropIndex("dbo.PolicyTransactions", "IX_PolicyTransactions_PolicyId");
        }
    }
}
