// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class QuoteReadModelAdditions : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Quotes", "FundingInternalId", c => c.Guid());
            AddColumn("dbo.Quotes", "FundingAcceptanceUrl", c => c.String());
            AddColumn("dbo.Quotes", "FundingProposalResponseJson", c => c.String());
            AddColumn("dbo.Quotes", "HadCustomerOnCreation", c => c.Boolean(nullable: false));
            AlterColumn("dbo.Quotes", "AmountFunded", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("dbo.Quotes", "FundingPaymentFrequency", c => c.Int());
            AlterColumn("dbo.Quotes", "FundingNumberOfInstallments", c => c.Int());
            AlterColumn("dbo.Quotes", "FundingInitialInstalmentAmount", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("dbo.Quotes", "FundingRegularInstalmentAmount", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("dbo.Quotes", "FundingTicksSinceEpoch", c => c.Long());
        }
        
        public override void Down()
        {
            Sql("Update dbo.Quotes SET FundingTicksSinceEpoch = 0 WHERE FundingTicksSinceEpoch IS NULL");
            AlterColumn("dbo.Quotes", "FundingTicksSinceEpoch", c => c.Long(nullable: false));
            Sql("Update dbo.Quotes SET FundingRegularInstalmentAmount = 0 WHERE FundingRegularInstalmentAmount IS NULL");
            AlterColumn("dbo.Quotes", "FundingRegularInstalmentAmount", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            Sql("Update dbo.Quotes SET FundingInitialInstalmentAmount = 0 WHERE FundingInitialInstalmentAmount IS NULL");
            AlterColumn("dbo.Quotes", "FundingInitialInstalmentAmount", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            Sql("Update dbo.Quotes SET FundingNumberOfInstallments = 0 WHERE FundingNumberOfInstallments IS NULL");
            AlterColumn("dbo.Quotes", "FundingNumberOfInstallments", c => c.Int(nullable: false));
            Sql("Update dbo.Quotes SET FundingPaymentFrequency = 0 WHERE FundingPaymentFrequency IS NULL");
            AlterColumn("dbo.Quotes", "FundingPaymentFrequency", c => c.Int(nullable: false));
            Sql("Update dbo.Quotes SET AmountFunded = 0 WHERE AmountFunded IS NULL");
            AlterColumn("dbo.Quotes", "AmountFunded", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            DropColumn("dbo.Quotes", "HadCustomerOnCreation");
            DropColumn("dbo.Quotes", "FundingProposalResponseJson");
            DropColumn("dbo.Quotes", "FundingAcceptanceUrl");
            DropColumn("dbo.Quotes", "FundingInternalId");
        }
    }
}
