// <auto-generated />

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class AddDataTableDefinitionEntity : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.DataTableDefinitions",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        TenantId = c.Guid(nullable: false),
                        EntityType = c.Int(nullable: false),
                        EntityId = c.Guid(nullable: false),
                        Name = c.String(),
                        Alias = c.String(),
                        DatabaseTableName = c.String(),
                        IsDeleted = c.Boolean(nullable: false),
                        RecordCount = c.Long(nullable: false),
                        LastModifiedTicksSinceEpoch = c.Long(nullable: false),
                        CreatedTicksSinceEpoch = c.Long(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .Index(t => t.TenantId, name: "AK_DataTableDefinitionTenantIndex")
                .Index(t => new { t.EntityType, t.EntityId }, name: "AK_DataTableDefinitionEntityTypeIndex");
            
        }
        
        public override void Down()
        {
            DropIndex("dbo.DataTableDefinitions", "AK_DataTableDefinitionEntityTypeIndex");
            DropIndex("dbo.DataTableDefinitions", "AK_DataTableDefinitionTenantIndex");
            DropTable("dbo.DataTableDefinitions");
        }
    }
}
