// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Helpers;

    public partial class RemoveFileEntity : DbMigration
    {
        private const String removeFilesEntityAlias = "RemoveFilesEntity_20230626";
        public override void Up()
        {
            this.Sql(StartupJobRunnerQueryHelper.GenerateInsertQueryForStartupJob(
            removeFilesEntityAlias, false, true));

            DropForeignKey("dbo.Assets", "ReleaseDetails_Id1", "dbo.ReleaseDetails");
            DropForeignKey("dbo.Files", "ReleaseDetails_Id", "dbo.ReleaseDetails");
            DropIndex("dbo.Files", new[] { "ReleaseDetails_Id" });
            AddForeignKey("dbo.Assets", "ReleaseDetails_Id1", "dbo.ReleaseDetails", "Id");
        }
        
        public override void Down()
        {
            this.Sql(StartupJobRunnerQueryHelper.GenerateDeleteQueryForStartupJob(
            removeFilesEntityAlias));
            this.Sql("IF OBJECT_ID('dbo.Files', 'U') IS NOT NULL DROP TABLE dbo.Files");
        }
    }
}
