// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class UpdatePolicyTransactionColumns : DbMigration
    {
        public override void Up()
        {
            this.Sql("UPDATE [dbo].[ProductFeatureSettings]"
                + "SET [AreNewBusinessPolicyTransactionsEnabled] = [AreNewBusinessQuotesEnabled],"
                + "[AreAdjustmentPolicyTransactionsEnabled] = [AreAdjustmentQuotesEnabled],"
                + "[AreCancellationPolicyTransactionsEnabled] = [AreCancellationQuotesEnabled],"
                + "[AreRenewalPolicyTransactionsEnabled] = [AreRenewalQuotesEnabled]");
        }

        public override void Down()
        {
        }
    }
}
