// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations;

using System.Data.Entity.Migrations;
using UBind.Persistence.Helpers;

public partial class RegenerateAggregateSnapshot : DbMigration
{
    private const string StartupJobAliasForAggregateSnapshot = "RegenerateAggregateSnapshot_06242024";

    public override void Up()
    {
        this.Sql(StartupJobRunnerQueryHelper.GenerateInsertQueryForStartupJob(StartupJobAliasForAggregateSnapshot));
    }

    public override void Down()
    {
        this.Sql(StartupJobRunnerQueryHelper.GenerateDeleteQueryForStartupJob(StartupJobAliasForAggregateSnapshot));
    }
}
