// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations;

using System.Data.Entity.Migrations;
using UBind.Persistence.Migrations.Extensions;

public partial class AddFundingInterestRateAndContractUrl : DbMigration
{
    public override void Up()
    {
        this.AddColumnIfNotExists("dbo.Quotes", "FundingContractUrl", c => c.String(nullable: true));
        this.AddColumnIfNotExists("dbo.Quotes", "FundingInstalmentInterestRate", c => c.Decimal(precision: 18, scale: 6, nullable: true));
    }

    public override void Down()
    {
        this.DropColumnIfExists("dbo.Quotes", "FundingInstalmentInterestRate");
        this.DropColumnIfExists("dbo.Quotes", "FundingContractUrl");
    }
}
