// <auto-generated />
#pragma warning disable 1591

namespace UBind.Persistence.Migrations;

using System.Data.Entity.Migrations;
using UBind.Persistence.Migrations.Extensions;

public partial class AddInstalmentMerchantFeeMultiplier : DbMigration
{
    public override void Up()
    {
        this.AddColumnIfNotExists("dbo.Quotes", "FundingInstalmentMerchantFeeMultiplier", c => c.Decimal(precision: 18, scale: 6));
    }

    public override void Down()
    {
        this.DropColumnIfExists("dbo.Quotes", "FundingInstalmentMerchantFeeMultiplier");
    }
}
