//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBind.Application.ConnectedServices.Funding.EFundExpress
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eFundExpressRate", Namespace="http://efund.com.au/express/")]
    public partial class eFundExpressRate : object
    {
        
        private Funding.EFundExpress.RateReturnType ReturnCodeField;
        
        private string ReturnMessageField;
        
        private float DomesticInterestRateField;
        
        private float CommercialInterestRateField;
        
        private float PBMPlusInterestRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Funding.EFundExpress.RateReturnType ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReturnMessage
        {
            get
            {
                return this.ReturnMessageField;
            }
            set
            {
                this.ReturnMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float DomesticInterestRate
        {
            get
            {
                return this.DomesticInterestRateField;
            }
            set
            {
                this.DomesticInterestRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float CommercialInterestRate
        {
            get
            {
                return this.CommercialInterestRateField;
            }
            set
            {
                this.CommercialInterestRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float PBMPlusInterestRate
        {
            get
            {
                return this.PBMPlusInterestRateField;
            }
            set
            {
                this.PBMPlusInterestRateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateReturnType", Namespace="http://efund.com.au/express/")]
    public enum RateReturnType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eFundExpressObject", Namespace="http://efund.com.au/express/")]
    public partial class eFundExpressObject : object
    {
        
        private string ClientRequestIDField;
        
        private string BrokerLoginIDField;
        
        private string PasswordField;
        
        private string TypeOfContractField;
        
        private int IssueOptionField;
        
        private int IssueCopyField;
        
        private string ClientNameField;
        
        private string ContactPersonField;
        
        private string DirectorNameField;
        
        private string ClientABNField;
        
        private string ClientDOBField;
        
        private string StreetAddress1Field;
        
        private string StreetAddress2Field;
        
        private string StreetSuburbField;
        
        private string StreetStateField;
        
        private string StreetPostcodeField;
        
        private string ClientPhoneField;
        
        private string ClientMobileField;
        
        private string ClientFaxField;
        
        private string ClientEmailField;
        
        private Funding.EFundExpress.ClientPolicy[] ClientPoliciesField;
        
        private System.Nullable<int> FundingPeriodField;
        
        private string BrokerURLField;
        
        private string BrokerExitURLField;
        
        private string ClientCodeField;
        
        private string FortnightlyInstalmentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientRequestID
        {
            get
            {
                return this.ClientRequestIDField;
            }
            set
            {
                this.ClientRequestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BrokerLoginID
        {
            get
            {
                return this.BrokerLoginIDField;
            }
            set
            {
                this.BrokerLoginIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TypeOfContract
        {
            get
            {
                return this.TypeOfContractField;
            }
            set
            {
                this.TypeOfContractField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int IssueOption
        {
            get
            {
                return this.IssueOptionField;
            }
            set
            {
                this.IssueOptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int IssueCopy
        {
            get
            {
                return this.IssueCopyField;
            }
            set
            {
                this.IssueCopyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ClientName
        {
            get
            {
                return this.ClientNameField;
            }
            set
            {
                this.ClientNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ContactPerson
        {
            get
            {
                return this.ContactPersonField;
            }
            set
            {
                this.ContactPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DirectorName
        {
            get
            {
                return this.DirectorNameField;
            }
            set
            {
                this.DirectorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ClientABN
        {
            get
            {
                return this.ClientABNField;
            }
            set
            {
                this.ClientABNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ClientDOB
        {
            get
            {
                return this.ClientDOBField;
            }
            set
            {
                this.ClientDOBField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string StreetAddress1
        {
            get
            {
                return this.StreetAddress1Field;
            }
            set
            {
                this.StreetAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string StreetAddress2
        {
            get
            {
                return this.StreetAddress2Field;
            }
            set
            {
                this.StreetAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string StreetSuburb
        {
            get
            {
                return this.StreetSuburbField;
            }
            set
            {
                this.StreetSuburbField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string StreetState
        {
            get
            {
                return this.StreetStateField;
            }
            set
            {
                this.StreetStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string StreetPostcode
        {
            get
            {
                return this.StreetPostcodeField;
            }
            set
            {
                this.StreetPostcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ClientPhone
        {
            get
            {
                return this.ClientPhoneField;
            }
            set
            {
                this.ClientPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ClientMobile
        {
            get
            {
                return this.ClientMobileField;
            }
            set
            {
                this.ClientMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string ClientFax
        {
            get
            {
                return this.ClientFaxField;
            }
            set
            {
                this.ClientFaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string ClientEmail
        {
            get
            {
                return this.ClientEmailField;
            }
            set
            {
                this.ClientEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public Funding.EFundExpress.ClientPolicy[] ClientPolicies
        {
            get
            {
                return this.ClientPoliciesField;
            }
            set
            {
                this.ClientPoliciesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<int> FundingPeriod
        {
            get
            {
                return this.FundingPeriodField;
            }
            set
            {
                this.FundingPeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string BrokerURL
        {
            get
            {
                return this.BrokerURLField;
            }
            set
            {
                this.BrokerURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string BrokerExitURL
        {
            get
            {
                return this.BrokerExitURLField;
            }
            set
            {
                this.BrokerExitURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ClientCode
        {
            get
            {
                return this.ClientCodeField;
            }
            set
            {
                this.ClientCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string FortnightlyInstalments
        {
            get
            {
                return this.FortnightlyInstalmentsField;
            }
            set
            {
                this.FortnightlyInstalmentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientPolicy", Namespace="http://efund.com.au/express/")]
    public partial class ClientPolicy : object
    {
        
        private string UnderwriterNameField;
        
        private string PolicyClassField;
        
        private string PolicyNumberField;
        
        private string PolicyInceptionField;
        
        private string PolicyExpiryField;
        
        private string PolicyPremiumField;
        
        private string PolicyInvoiceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UnderwriterName
        {
            get
            {
                return this.UnderwriterNameField;
            }
            set
            {
                this.UnderwriterNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PolicyClass
        {
            get
            {
                return this.PolicyClassField;
            }
            set
            {
                this.PolicyClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PolicyInception
        {
            get
            {
                return this.PolicyInceptionField;
            }
            set
            {
                this.PolicyInceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PolicyExpiry
        {
            get
            {
                return this.PolicyExpiryField;
            }
            set
            {
                this.PolicyExpiryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PolicyPremium
        {
            get
            {
                return this.PolicyPremiumField;
            }
            set
            {
                this.PolicyPremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PolicyInvoice
        {
            get
            {
                return this.PolicyInvoiceField;
            }
            set
            {
                this.PolicyInvoiceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eFundExpressQuote", Namespace="http://efund.com.au/express/")]
    public partial class eFundExpressQuote : object
    {
        
        private int ContractIDField;
        
        private Funding.EFundExpress.ReturnType ReturnCodeField;
        
        private string ReturnMessageField;
        
        private byte[] ContractPDFField;
        
        private byte[] TermsAndConditionsPDFField;
        
        private string eFundLinkField;
        
        private string ClientRequestIDField;
        
        private string eFundLoginTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ContractID
        {
            get
            {
                return this.ContractIDField;
            }
            set
            {
                this.ContractIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Funding.EFundExpress.ReturnType ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReturnMessage
        {
            get
            {
                return this.ReturnMessageField;
            }
            set
            {
                this.ReturnMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContractPDF
        {
            get
            {
                return this.ContractPDFField;
            }
            set
            {
                this.ContractPDFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] TermsAndConditionsPDF
        {
            get
            {
                return this.TermsAndConditionsPDFField;
            }
            set
            {
                this.TermsAndConditionsPDFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string eFundLink
        {
            get
            {
                return this.eFundLinkField;
            }
            set
            {
                this.eFundLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ClientRequestID
        {
            get
            {
                return this.ClientRequestIDField;
            }
            set
            {
                this.ClientRequestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string eFundLoginText
        {
            get
            {
                return this.eFundLoginTextField;
            }
            set
            {
                this.eFundLoginTextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnType", Namespace="http://efund.com.au/express/")]
    public enum ReturnType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfEFundExpressObject", Namespace="http://efund.com.au/express/", ItemName="eFundExpressObject")]
    public class ArrayOfEFundExpressObject : System.Collections.Generic.List<Funding.EFundExpress.eFundExpressObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfEFundExpressQuote", Namespace="http://efund.com.au/express/", ItemName="eFundExpressQuote")]
    public class ArrayOfEFundExpressQuote : System.Collections.Generic.List<Funding.EFundExpress.eFundExpressQuote>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eFundExpressURL", Namespace="http://efund.com.au/express/")]
    public partial class eFundExpressURL : object
    {
        
        private Funding.EFundExpress.UrlReturnType ReturnCodeField;
        
        private string ReturnMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Funding.EFundExpress.UrlReturnType ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReturnMessage
        {
            get
            {
                return this.ReturnMessageField;
            }
            set
            {
                this.ReturnMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrlReturnType", Namespace="http://efund.com.au/express/")]
    public enum UrlReturnType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eFundExpressDocument", Namespace="http://efund.com.au/express/")]
    public partial class eFundExpressDocument : object
    {
        
        private int ContractIDField;
        
        private Funding.EFundExpress.AcceptedReturnType ReturnCodeField;
        
        private string ReturnMessageField;
        
        private byte[] ContractPDFField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ContractID
        {
            get
            {
                return this.ContractIDField;
            }
            set
            {
                this.ContractIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Funding.EFundExpress.AcceptedReturnType ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReturnMessage
        {
            get
            {
                return this.ReturnMessageField;
            }
            set
            {
                this.ReturnMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContractPDF
        {
            get
            {
                return this.ContractPDFField;
            }
            set
            {
                this.ContractPDFField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcceptedReturnType", Namespace="http://efund.com.au/express/")]
    public enum AcceptedReturnType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="easyBondpayInstalments", Namespace="http://efund.com.au/express/")]
    public partial class easyBondpayInstalments : object
    {
        
        private Funding.EFundExpress.InstallmentReturnType ReturnCodeField;
        
        private string ReturnMessageField;
        
        private decimal FirstInstalmentField;
        
        private decimal RemainingInstalmentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Funding.EFundExpress.InstallmentReturnType ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReturnMessage
        {
            get
            {
                return this.ReturnMessageField;
            }
            set
            {
                this.ReturnMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal FirstInstalment
        {
            get
            {
                return this.FirstInstalmentField;
            }
            set
            {
                this.FirstInstalmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal RemainingInstalment
        {
            get
            {
                return this.RemainingInstalmentField;
            }
            set
            {
                this.RemainingInstalmentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstallmentReturnType", Namespace="http://efund.com.au/express/")]
    public enum InstallmentReturnType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="easyBondpayObject", Namespace="http://efund.com.au/express/")]
    public partial class easyBondpayObject : object
    {
        
        private string ClientRequestIDField;
        
        private string BrokerLoginIDField;
        
        private string PasswordField;
        
        private int IssueOptionField;
        
        private int IssueCopyField;
        
        private string StreetAddress1Field;
        
        private string StreetAddress2Field;
        
        private string StreetSuburbField;
        
        private string StreetStateField;
        
        private string StreetPostcodeField;
        
        private string ApplicantNameField;
        
        private string ClientCodeField;
        
        private string ClientPhoneField;
        
        private string ClientFaxField;
        
        private string ClientMobileField;
        
        private string ClientEmailField;
        
        private string PropertyManagerField;
        
        private string ContactNameField;
        
        private decimal BondAmountField;
        
        private System.Nullable<int> FinancePeriodField;
        
        private string BrokerURLField;
        
        private string BrokerExitURLField;
        
        private string PMAgencyIDField;
        
        private string PMUserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientRequestID
        {
            get
            {
                return this.ClientRequestIDField;
            }
            set
            {
                this.ClientRequestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BrokerLoginID
        {
            get
            {
                return this.BrokerLoginIDField;
            }
            set
            {
                this.BrokerLoginIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IssueOption
        {
            get
            {
                return this.IssueOptionField;
            }
            set
            {
                this.IssueOptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int IssueCopy
        {
            get
            {
                return this.IssueCopyField;
            }
            set
            {
                this.IssueCopyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StreetAddress1
        {
            get
            {
                return this.StreetAddress1Field;
            }
            set
            {
                this.StreetAddress1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string StreetAddress2
        {
            get
            {
                return this.StreetAddress2Field;
            }
            set
            {
                this.StreetAddress2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string StreetSuburb
        {
            get
            {
                return this.StreetSuburbField;
            }
            set
            {
                this.StreetSuburbField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string StreetState
        {
            get
            {
                return this.StreetStateField;
            }
            set
            {
                this.StreetStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string StreetPostcode
        {
            get
            {
                return this.StreetPostcodeField;
            }
            set
            {
                this.StreetPostcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ApplicantName
        {
            get
            {
                return this.ApplicantNameField;
            }
            set
            {
                this.ApplicantNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ClientCode
        {
            get
            {
                return this.ClientCodeField;
            }
            set
            {
                this.ClientCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ClientPhone
        {
            get
            {
                return this.ClientPhoneField;
            }
            set
            {
                this.ClientPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ClientFax
        {
            get
            {
                return this.ClientFaxField;
            }
            set
            {
                this.ClientFaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ClientMobile
        {
            get
            {
                return this.ClientMobileField;
            }
            set
            {
                this.ClientMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ClientEmail
        {
            get
            {
                return this.ClientEmailField;
            }
            set
            {
                this.ClientEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string PropertyManager
        {
            get
            {
                return this.PropertyManagerField;
            }
            set
            {
                this.PropertyManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                this.ContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public decimal BondAmount
        {
            get
            {
                return this.BondAmountField;
            }
            set
            {
                this.BondAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.Nullable<int> FinancePeriod
        {
            get
            {
                return this.FinancePeriodField;
            }
            set
            {
                this.FinancePeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string BrokerURL
        {
            get
            {
                return this.BrokerURLField;
            }
            set
            {
                this.BrokerURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string BrokerExitURL
        {
            get
            {
                return this.BrokerExitURLField;
            }
            set
            {
                this.BrokerExitURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string PMAgencyID
        {
            get
            {
                return this.PMAgencyIDField;
            }
            set
            {
                this.PMAgencyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string PMUserID
        {
            get
            {
                return this.PMUserIDField;
            }
            set
            {
                this.PMUserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="easyBondpayQuote", Namespace="http://efund.com.au/express/")]
    public partial class easyBondpayQuote : object
    {
        
        private int ContractIDField;
        
        private Funding.EFundExpress.ReturnType ReturnCodeField;
        
        private string ReturnMessageField;
        
        private byte[] ContractPDFField;
        
        private string eFundLinkField;
        
        private string ClientRequestIDField;
        
        private string eFundLoginTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ContractID
        {
            get
            {
                return this.ContractIDField;
            }
            set
            {
                this.ContractIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Funding.EFundExpress.ReturnType ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReturnMessage
        {
            get
            {
                return this.ReturnMessageField;
            }
            set
            {
                this.ReturnMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContractPDF
        {
            get
            {
                return this.ContractPDFField;
            }
            set
            {
                this.ContractPDFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string eFundLink
        {
            get
            {
                return this.eFundLinkField;
            }
            set
            {
                this.eFundLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ClientRequestID
        {
            get
            {
                return this.ClientRequestIDField;
            }
            set
            {
                this.ClientRequestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string eFundLoginText
        {
            get
            {
                return this.eFundLoginTextField;
            }
            set
            {
                this.eFundLoginTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eFundExpressStatus", Namespace="http://efund.com.au/express/")]
    public partial class eFundExpressStatus : object
    {
        
        private Funding.EFundExpress.StatusReturnType ReturnCodeField;
        
        private string ReturnMessageField;
        
        private Funding.EFundExpress.ContractsStatuses[] ContractsStatusesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Funding.EFundExpress.StatusReturnType ReturnCode
        {
            get
            {
                return this.ReturnCodeField;
            }
            set
            {
                this.ReturnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReturnMessage
        {
            get
            {
                return this.ReturnMessageField;
            }
            set
            {
                this.ReturnMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Funding.EFundExpress.ContractsStatuses[] ContractsStatuses
        {
            get
            {
                return this.ContractsStatusesField;
            }
            set
            {
                this.ContractsStatusesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusReturnType", Namespace="http://efund.com.au/express/")]
    public enum StatusReturnType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractsStatuses", Namespace="http://efund.com.au/express/")]
    public partial class ContractsStatuses : object
    {
        
        private int ContractIDField;
        
        private Funding.EFundExpress.ContractStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ContractID
        {
            get
            {
                return this.ContractIDField;
            }
            set
            {
                this.ContractIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Funding.EFundExpress.ContractStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractStatus", Namespace="http://efund.com.au/express/")]
    public enum ContractStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quoted = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Denied = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://efund.com.au/express/", ConfigurationName="Funding.EFundExpress.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://efund.com.au/express/GetInterestRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Funding.EFundExpress.GetInterestRatesResponse> GetInterestRatesAsync(Funding.EFundExpress.GetInterestRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://efund.com.au/express/CreateFundingDocuments", ReplyAction="*")]
        System.Threading.Tasks.Task<Funding.EFundExpress.CreateFundingDocumentsResponse> CreateFundingDocumentsAsync(Funding.EFundExpress.CreateFundingDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://efund.com.au/express/CreateMultipleFundingDocuments", ReplyAction="*")]
        System.Threading.Tasks.Task<Funding.EFundExpress.CreateMultipleFundingDocumentsResponse> CreateMultipleFundingDocumentsAsync(Funding.EFundExpress.CreateMultipleFundingDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://efund.com.au/express/UpdateFundingUrls", ReplyAction="*")]
        System.Threading.Tasks.Task<Funding.EFundExpress.UpdateFundingUrlsResponse> UpdateFundingUrlsAsync(Funding.EFundExpress.UpdateFundingUrlsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://efund.com.au/express/GetAcceptedFundingDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<Funding.EFundExpress.GetAcceptedFundingDocumentResponse> GetAcceptedFundingDocumentAsync(Funding.EFundExpress.GetAcceptedFundingDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://efund.com.au/express/GeteasyBondpayInstalments", ReplyAction="*")]
        System.Threading.Tasks.Task<Funding.EFundExpress.GeteasyBondpayInstalmentsResponse> GeteasyBondpayInstalmentsAsync(Funding.EFundExpress.GeteasyBondpayInstalmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://efund.com.au/express/CreateeasyBondpayDocuments", ReplyAction="*")]
        System.Threading.Tasks.Task<Funding.EFundExpress.CreateeasyBondpayDocumentsResponse> CreateeasyBondpayDocumentsAsync(Funding.EFundExpress.CreateeasyBondpayDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://efund.com.au/express/GetContractStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Funding.EFundExpress.GetContractStatusResponse> GetContractStatusAsync(Funding.EFundExpress.GetContractStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInterestRatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInterestRates", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.GetInterestRatesRequestBody Body;
        
        public GetInterestRatesRequest()
        {
        }
        
        public GetInterestRatesRequest(Funding.EFundExpress.GetInterestRatesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class GetInterestRatesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BrokerLoginID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public GetInterestRatesRequestBody()
        {
        }
        
        public GetInterestRatesRequestBody(string BrokerLoginID, string Password)
        {
            this.BrokerLoginID = BrokerLoginID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInterestRatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInterestRatesResponse", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.GetInterestRatesResponseBody Body;
        
        public GetInterestRatesResponse()
        {
        }
        
        public GetInterestRatesResponse(Funding.EFundExpress.GetInterestRatesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class GetInterestRatesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.eFundExpressRate GetInterestRatesResult;
        
        public GetInterestRatesResponseBody()
        {
        }
        
        public GetInterestRatesResponseBody(Funding.EFundExpress.eFundExpressRate GetInterestRatesResult)
        {
            this.GetInterestRatesResult = GetInterestRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFundingDocumentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFundingDocuments", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.CreateFundingDocumentsRequestBody Body;
        
        public CreateFundingDocumentsRequest()
        {
        }
        
        public CreateFundingDocumentsRequest(Funding.EFundExpress.CreateFundingDocumentsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class CreateFundingDocumentsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.eFundExpressObject eFundExpress;
        
        public CreateFundingDocumentsRequestBody()
        {
        }
        
        public CreateFundingDocumentsRequestBody(Funding.EFundExpress.eFundExpressObject eFundExpress)
        {
            this.eFundExpress = eFundExpress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFundingDocumentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFundingDocumentsResponse", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.CreateFundingDocumentsResponseBody Body;
        
        public CreateFundingDocumentsResponse()
        {
        }
        
        public CreateFundingDocumentsResponse(Funding.EFundExpress.CreateFundingDocumentsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class CreateFundingDocumentsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.eFundExpressQuote CreateFundingDocumentsResult;
        
        public CreateFundingDocumentsResponseBody()
        {
        }
        
        public CreateFundingDocumentsResponseBody(Funding.EFundExpress.eFundExpressQuote CreateFundingDocumentsResult)
        {
            this.CreateFundingDocumentsResult = CreateFundingDocumentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMultipleFundingDocumentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMultipleFundingDocuments", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.CreateMultipleFundingDocumentsRequestBody Body;
        
        public CreateMultipleFundingDocumentsRequest()
        {
        }
        
        public CreateMultipleFundingDocumentsRequest(Funding.EFundExpress.CreateMultipleFundingDocumentsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class CreateMultipleFundingDocumentsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.ArrayOfEFundExpressObject eFundExpress;
        
        public CreateMultipleFundingDocumentsRequestBody()
        {
        }
        
        public CreateMultipleFundingDocumentsRequestBody(Funding.EFundExpress.ArrayOfEFundExpressObject eFundExpress)
        {
            this.eFundExpress = eFundExpress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMultipleFundingDocumentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMultipleFundingDocumentsResponse", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.CreateMultipleFundingDocumentsResponseBody Body;
        
        public CreateMultipleFundingDocumentsResponse()
        {
        }
        
        public CreateMultipleFundingDocumentsResponse(Funding.EFundExpress.CreateMultipleFundingDocumentsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class CreateMultipleFundingDocumentsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.ArrayOfEFundExpressQuote CreateMultipleFundingDocumentsResult;
        
        public CreateMultipleFundingDocumentsResponseBody()
        {
        }
        
        public CreateMultipleFundingDocumentsResponseBody(Funding.EFundExpress.ArrayOfEFundExpressQuote CreateMultipleFundingDocumentsResult)
        {
            this.CreateMultipleFundingDocumentsResult = CreateMultipleFundingDocumentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFundingUrlsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFundingUrls", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.UpdateFundingUrlsRequestBody Body;
        
        public UpdateFundingUrlsRequest()
        {
        }
        
        public UpdateFundingUrlsRequest(Funding.EFundExpress.UpdateFundingUrlsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class UpdateFundingUrlsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BrokerLoginID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BrokerExitURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BrokerURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ContractID;
        
        public UpdateFundingUrlsRequestBody()
        {
        }
        
        public UpdateFundingUrlsRequestBody(string BrokerLoginID, string Password, string BrokerExitURL, string BrokerURL, int ContractID)
        {
            this.BrokerLoginID = BrokerLoginID;
            this.Password = Password;
            this.BrokerExitURL = BrokerExitURL;
            this.BrokerURL = BrokerURL;
            this.ContractID = ContractID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFundingUrlsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFundingUrlsResponse", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.UpdateFundingUrlsResponseBody Body;
        
        public UpdateFundingUrlsResponse()
        {
        }
        
        public UpdateFundingUrlsResponse(Funding.EFundExpress.UpdateFundingUrlsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class UpdateFundingUrlsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.eFundExpressURL UpdateFundingUrlsResult;
        
        public UpdateFundingUrlsResponseBody()
        {
        }
        
        public UpdateFundingUrlsResponseBody(Funding.EFundExpress.eFundExpressURL UpdateFundingUrlsResult)
        {
            this.UpdateFundingUrlsResult = UpdateFundingUrlsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAcceptedFundingDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAcceptedFundingDocument", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.GetAcceptedFundingDocumentRequestBody Body;
        
        public GetAcceptedFundingDocumentRequest()
        {
        }
        
        public GetAcceptedFundingDocumentRequest(Funding.EFundExpress.GetAcceptedFundingDocumentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class GetAcceptedFundingDocumentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BrokerLoginID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ContractID;
        
        public GetAcceptedFundingDocumentRequestBody()
        {
        }
        
        public GetAcceptedFundingDocumentRequestBody(string BrokerLoginID, string Password, int ContractID)
        {
            this.BrokerLoginID = BrokerLoginID;
            this.Password = Password;
            this.ContractID = ContractID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAcceptedFundingDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAcceptedFundingDocumentResponse", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.GetAcceptedFundingDocumentResponseBody Body;
        
        public GetAcceptedFundingDocumentResponse()
        {
        }
        
        public GetAcceptedFundingDocumentResponse(Funding.EFundExpress.GetAcceptedFundingDocumentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class GetAcceptedFundingDocumentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.eFundExpressDocument GetAcceptedFundingDocumentResult;
        
        public GetAcceptedFundingDocumentResponseBody()
        {
        }
        
        public GetAcceptedFundingDocumentResponseBody(Funding.EFundExpress.eFundExpressDocument GetAcceptedFundingDocumentResult)
        {
            this.GetAcceptedFundingDocumentResult = GetAcceptedFundingDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeteasyBondpayInstalmentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeteasyBondpayInstalments", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.GeteasyBondpayInstalmentsRequestBody Body;
        
        public GeteasyBondpayInstalmentsRequest()
        {
        }
        
        public GeteasyBondpayInstalmentsRequest(Funding.EFundExpress.GeteasyBondpayInstalmentsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class GeteasyBondpayInstalmentsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BrokerLoginID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int FinancePeriod;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal BondAmount;
        
        public GeteasyBondpayInstalmentsRequestBody()
        {
        }
        
        public GeteasyBondpayInstalmentsRequestBody(string BrokerLoginID, string Password, int FinancePeriod, decimal BondAmount)
        {
            this.BrokerLoginID = BrokerLoginID;
            this.Password = Password;
            this.FinancePeriod = FinancePeriod;
            this.BondAmount = BondAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GeteasyBondpayInstalmentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GeteasyBondpayInstalmentsResponse", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.GeteasyBondpayInstalmentsResponseBody Body;
        
        public GeteasyBondpayInstalmentsResponse()
        {
        }
        
        public GeteasyBondpayInstalmentsResponse(Funding.EFundExpress.GeteasyBondpayInstalmentsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class GeteasyBondpayInstalmentsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.easyBondpayInstalments GeteasyBondpayInstalmentsResult;
        
        public GeteasyBondpayInstalmentsResponseBody()
        {
        }
        
        public GeteasyBondpayInstalmentsResponseBody(Funding.EFundExpress.easyBondpayInstalments GeteasyBondpayInstalmentsResult)
        {
            this.GeteasyBondpayInstalmentsResult = GeteasyBondpayInstalmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateeasyBondpayDocumentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateeasyBondpayDocuments", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.CreateeasyBondpayDocumentsRequestBody Body;
        
        public CreateeasyBondpayDocumentsRequest()
        {
        }
        
        public CreateeasyBondpayDocumentsRequest(Funding.EFundExpress.CreateeasyBondpayDocumentsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class CreateeasyBondpayDocumentsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.easyBondpayObject easyBondpayExpress;
        
        public CreateeasyBondpayDocumentsRequestBody()
        {
        }
        
        public CreateeasyBondpayDocumentsRequestBody(Funding.EFundExpress.easyBondpayObject easyBondpayExpress)
        {
            this.easyBondpayExpress = easyBondpayExpress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateeasyBondpayDocumentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateeasyBondpayDocumentsResponse", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.CreateeasyBondpayDocumentsResponseBody Body;
        
        public CreateeasyBondpayDocumentsResponse()
        {
        }
        
        public CreateeasyBondpayDocumentsResponse(Funding.EFundExpress.CreateeasyBondpayDocumentsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class CreateeasyBondpayDocumentsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.easyBondpayQuote CreateeasyBondpayDocumentsResult;
        
        public CreateeasyBondpayDocumentsResponseBody()
        {
        }
        
        public CreateeasyBondpayDocumentsResponseBody(Funding.EFundExpress.easyBondpayQuote CreateeasyBondpayDocumentsResult)
        {
            this.CreateeasyBondpayDocumentsResult = CreateeasyBondpayDocumentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContractStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContractStatus", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.GetContractStatusRequestBody Body;
        
        public GetContractStatusRequest()
        {
        }
        
        public GetContractStatusRequest(Funding.EFundExpress.GetContractStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class GetContractStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BrokerLoginID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ContractID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastModified;
        
        public GetContractStatusRequestBody()
        {
        }
        
        public GetContractStatusRequestBody(string BrokerLoginID, string Password, string ContractID, string LastModified)
        {
            this.BrokerLoginID = BrokerLoginID;
            this.Password = Password;
            this.ContractID = ContractID;
            this.LastModified = LastModified;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContractStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContractStatusResponse", Namespace="http://efund.com.au/express/", Order=0)]
        public Funding.EFundExpress.GetContractStatusResponseBody Body;
        
        public GetContractStatusResponse()
        {
        }
        
        public GetContractStatusResponse(Funding.EFundExpress.GetContractStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://efund.com.au/express/")]
    public partial class GetContractStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Funding.EFundExpress.eFundExpressStatus GetContractStatusResult;
        
        public GetContractStatusResponseBody()
        {
        }
        
        public GetContractStatusResponseBody(Funding.EFundExpress.eFundExpressStatus GetContractStatusResult)
        {
            this.GetContractStatusResult = GetContractStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceSoapChannel : Funding.EFundExpress.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Funding.EFundExpress.ServiceSoap>, Funding.EFundExpress.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Funding.EFundExpress.GetInterestRatesResponse> Funding.EFundExpress.ServiceSoap.GetInterestRatesAsync(Funding.EFundExpress.GetInterestRatesRequest request)
        {
            return base.Channel.GetInterestRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Funding.EFundExpress.GetInterestRatesResponse> GetInterestRatesAsync(string BrokerLoginID, string Password)
        {
            Funding.EFundExpress.GetInterestRatesRequest inValue = new Funding.EFundExpress.GetInterestRatesRequest();
            inValue.Body = new Funding.EFundExpress.GetInterestRatesRequestBody();
            inValue.Body.BrokerLoginID = BrokerLoginID;
            inValue.Body.Password = Password;
            return ((Funding.EFundExpress.ServiceSoap)(this)).GetInterestRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Funding.EFundExpress.CreateFundingDocumentsResponse> Funding.EFundExpress.ServiceSoap.CreateFundingDocumentsAsync(Funding.EFundExpress.CreateFundingDocumentsRequest request)
        {
            return base.Channel.CreateFundingDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Funding.EFundExpress.CreateFundingDocumentsResponse> CreateFundingDocumentsAsync(Funding.EFundExpress.eFundExpressObject eFundExpress)
        {
            Funding.EFundExpress.CreateFundingDocumentsRequest inValue = new Funding.EFundExpress.CreateFundingDocumentsRequest();
            inValue.Body = new Funding.EFundExpress.CreateFundingDocumentsRequestBody();
            inValue.Body.eFundExpress = eFundExpress;
            return ((Funding.EFundExpress.ServiceSoap)(this)).CreateFundingDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Funding.EFundExpress.CreateMultipleFundingDocumentsResponse> Funding.EFundExpress.ServiceSoap.CreateMultipleFundingDocumentsAsync(Funding.EFundExpress.CreateMultipleFundingDocumentsRequest request)
        {
            return base.Channel.CreateMultipleFundingDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Funding.EFundExpress.CreateMultipleFundingDocumentsResponse> CreateMultipleFundingDocumentsAsync(Funding.EFundExpress.ArrayOfEFundExpressObject eFundExpress)
        {
            Funding.EFundExpress.CreateMultipleFundingDocumentsRequest inValue = new Funding.EFundExpress.CreateMultipleFundingDocumentsRequest();
            inValue.Body = new Funding.EFundExpress.CreateMultipleFundingDocumentsRequestBody();
            inValue.Body.eFundExpress = eFundExpress;
            return ((Funding.EFundExpress.ServiceSoap)(this)).CreateMultipleFundingDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Funding.EFundExpress.UpdateFundingUrlsResponse> Funding.EFundExpress.ServiceSoap.UpdateFundingUrlsAsync(Funding.EFundExpress.UpdateFundingUrlsRequest request)
        {
            return base.Channel.UpdateFundingUrlsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Funding.EFundExpress.UpdateFundingUrlsResponse> UpdateFundingUrlsAsync(string BrokerLoginID, string Password, string BrokerExitURL, string BrokerURL, int ContractID)
        {
            Funding.EFundExpress.UpdateFundingUrlsRequest inValue = new Funding.EFundExpress.UpdateFundingUrlsRequest();
            inValue.Body = new Funding.EFundExpress.UpdateFundingUrlsRequestBody();
            inValue.Body.BrokerLoginID = BrokerLoginID;
            inValue.Body.Password = Password;
            inValue.Body.BrokerExitURL = BrokerExitURL;
            inValue.Body.BrokerURL = BrokerURL;
            inValue.Body.ContractID = ContractID;
            return ((Funding.EFundExpress.ServiceSoap)(this)).UpdateFundingUrlsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Funding.EFundExpress.GetAcceptedFundingDocumentResponse> Funding.EFundExpress.ServiceSoap.GetAcceptedFundingDocumentAsync(Funding.EFundExpress.GetAcceptedFundingDocumentRequest request)
        {
            return base.Channel.GetAcceptedFundingDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Funding.EFundExpress.GetAcceptedFundingDocumentResponse> GetAcceptedFundingDocumentAsync(string BrokerLoginID, string Password, int ContractID)
        {
            Funding.EFundExpress.GetAcceptedFundingDocumentRequest inValue = new Funding.EFundExpress.GetAcceptedFundingDocumentRequest();
            inValue.Body = new Funding.EFundExpress.GetAcceptedFundingDocumentRequestBody();
            inValue.Body.BrokerLoginID = BrokerLoginID;
            inValue.Body.Password = Password;
            inValue.Body.ContractID = ContractID;
            return ((Funding.EFundExpress.ServiceSoap)(this)).GetAcceptedFundingDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Funding.EFundExpress.GeteasyBondpayInstalmentsResponse> Funding.EFundExpress.ServiceSoap.GeteasyBondpayInstalmentsAsync(Funding.EFundExpress.GeteasyBondpayInstalmentsRequest request)
        {
            return base.Channel.GeteasyBondpayInstalmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Funding.EFundExpress.GeteasyBondpayInstalmentsResponse> GeteasyBondpayInstalmentsAsync(string BrokerLoginID, string Password, int FinancePeriod, decimal BondAmount)
        {
            Funding.EFundExpress.GeteasyBondpayInstalmentsRequest inValue = new Funding.EFundExpress.GeteasyBondpayInstalmentsRequest();
            inValue.Body = new Funding.EFundExpress.GeteasyBondpayInstalmentsRequestBody();
            inValue.Body.BrokerLoginID = BrokerLoginID;
            inValue.Body.Password = Password;
            inValue.Body.FinancePeriod = FinancePeriod;
            inValue.Body.BondAmount = BondAmount;
            return ((Funding.EFundExpress.ServiceSoap)(this)).GeteasyBondpayInstalmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Funding.EFundExpress.CreateeasyBondpayDocumentsResponse> Funding.EFundExpress.ServiceSoap.CreateeasyBondpayDocumentsAsync(Funding.EFundExpress.CreateeasyBondpayDocumentsRequest request)
        {
            return base.Channel.CreateeasyBondpayDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Funding.EFundExpress.CreateeasyBondpayDocumentsResponse> CreateeasyBondpayDocumentsAsync(Funding.EFundExpress.easyBondpayObject easyBondpayExpress)
        {
            Funding.EFundExpress.CreateeasyBondpayDocumentsRequest inValue = new Funding.EFundExpress.CreateeasyBondpayDocumentsRequest();
            inValue.Body = new Funding.EFundExpress.CreateeasyBondpayDocumentsRequestBody();
            inValue.Body.easyBondpayExpress = easyBondpayExpress;
            return ((Funding.EFundExpress.ServiceSoap)(this)).CreateeasyBondpayDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Funding.EFundExpress.GetContractStatusResponse> Funding.EFundExpress.ServiceSoap.GetContractStatusAsync(Funding.EFundExpress.GetContractStatusRequest request)
        {
            return base.Channel.GetContractStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Funding.EFundExpress.GetContractStatusResponse> GetContractStatusAsync(string BrokerLoginID, string Password, string ContractID, string LastModified)
        {
            Funding.EFundExpress.GetContractStatusRequest inValue = new Funding.EFundExpress.GetContractStatusRequest();
            inValue.Body = new Funding.EFundExpress.GetContractStatusRequestBody();
            inValue.Body.BrokerLoginID = BrokerLoginID;
            inValue.Body.Password = Password;
            inValue.Body.ContractID = ContractID;
            inValue.Body.LastModified = LastModified;
            return ((Funding.EFundExpress.ServiceSoap)(this)).GetContractStatusAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap1))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://odyssey.redplanetsoftware.com/principal/integration/principal/service.asm" +
                        "x");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap1))
            {
                return new System.ServiceModel.EndpointAddress("https://odyssey.redplanetsoftware.com/principal/integration/principal/service.asm" +
                        "x");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap1,
        }
    }
}
