export const storageHelper: any = {
    user: {
        accessToken: 'ubind.accessToken',
        expiryTime: 'ubind.expiryTime',
        userId: 'ubind.userId',
        customerId: 'ubind.customerId',
        tenantId: 'ubind.tenantId',
        tenantAlias: 'ubind.tenantAlias',
        portalId: 'ubind.portalId',
        emailAddress: 'ubind.emailAddress',
        fullName: 'ubind.fullName',
        preferredName: 'ubind.preferredName',
        userType: 'ubind.userType',
        environment: 'ubind.environment',
        permissions: 'ubind.permissions',
        organisationId: 'ubind.organisationId',
        organisationAlias: 'ubind.organisationAlias',
        profilePictureId: 'ubind.profilePictureId',
        portalOrganisationId: 'ubind.portalOrganisationId',
        portalOrganisationAlias: 'ubind.portalOrganisationAlias',
        authenticationMethodId: 'ubind.authenticationMethodId',
        authenticationMethodType: 'ubind.authenticationMethodType',
        supportsSingleLogout: 'ubind.supportsSingleLogout',
    },
};
