// <copyright file="IProductConfiguration.cs" company="uBind">
// Copyright (c) uBind. All rights reserved.
// </copyright>

// If you edit this file, you must remove this line and then do proper null checking
#pragma warning disable CS8600, CS8625, CS8629, CS8618, CS8605, CS8604, CS8601, CS8602, CS8603, CS8622, CS8619, CS8767, CS8620, CS8765

namespace UBind.Domain.Configuration
{
    using UBind.Domain.Aggregates.Claim.Workflow;
    using UBind.Domain.Aggregates.Quote.DataLocator;
    using UBind.Domain.Aggregates.Quote.Workflow;
    using UBind.Domain.NumberGenerators;

    /// <summary>
    /// Configuration for a product.
    /// </summary>
    public interface IProductConfiguration : IDataLocatorConfig
    {
        /// <summary>
        /// Gets the source to use for quote numbers, e.g. preloaded or autogenerated.
        /// </summary>
        NumberSource QuoteNumberSource { get; }

        /// <summary>
        /// Gets the obfuscation method to use for auto generated numbers.
        /// </summary>
        NumberObfuscationMethod NumberObfuscationMethod { get; }

        /// <summary>
        /// Gets the configurable quote workflow logic configuration to be used for the product.
        /// </summary>
        IQuoteWorkflow QuoteWorkflow { get; }

        /// <summary>
        /// Gets the configurable claim workflow logic configuration to be used for the product.
        /// </summary>
        IClaimWorkflow ClaimWorkflow { get; }

        /// <summary>
        /// Gets the form data schema.
        /// </summary>
        IFormDataSchema FormDataSchema { get; }

        /// <summary>
        /// Gets the default context entities which are loaded for all quote transaction types.
        /// </summary>
        /// <remarks>
        /// This is an optional property which should be applied to all quoteTypes as the default option.
        /// </remarks>
        IContextEntities ContextEntities { get; }
    }
}
