// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence.ThirdPartyDataSets
{
    using System.Data.Entity.Migrations;
    
    public partial class RenameDateFields : DbMigration
    {
        public override void Up()
        {
            RenameColumn("JobScheduler.StateMachineJob", "StartTimeAsTicksSinceEpoch", "StartTicksSinceEpoch");
            RenameColumn("JobScheduler.StateMachineJob", "CreationTimeInTicksSinceEpoch", "CreatedTicksSinceEpoch");
            DropColumn("JobScheduler.StateMachineJob", "EndTimeAsTicksSinceEpoch");
        }
        
        public override void Down()
        {
            AddColumn("JobScheduler.StateMachineJob", "EndTimeAsTicksSinceEpoch", c => c.Long());
            RenameColumn("JobScheduler.StateMachineJob", "CreatedTicksSinceEpoch", "CreationTimeInTicksSinceEpoch");
            RenameColumn("JobScheduler.StateMachineJob", "StartTicksSinceEpoch", "StartTimeAsTicksSinceEpoch");
        }
    }
}
