// <auto-generated />
namespace UBind.Persistence.ThirdPartyDataSets
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CreateTableBoundedView : DbMigration
    {
        public override void Up()
        {
            var createTableBoundedViewScript = Path.Combine(
                AppDomain.CurrentDomain.BaseDirectory, "ThirdPartyDataSets", "Migrations", "Scripts", @"CreateTableBoundedViewsBySchema.sql");
            this.Sql(File.ReadAllText(createTableBoundedViewScript));
        }
        
        public override void Down()
        {
            var dropTableBoundedViewScript = Path.Combine(
                AppDomain.CurrentDomain.BaseDirectory, "ThirdPartyDataSets", "Migrations", "Scripts", @"DropTableBoundedViewsBySchema.sql");
            this.Sql(File.ReadAllText(dropTableBoundedViewScript));
        }
    }
}
