// <auto-generated />
namespace UBind.Persistence.ThirdPartyDataSets
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddEndDateTimeFieldToStateMachineJobTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEndDateTimeFieldToStateMachineJobTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202402160554211_AddEndDateTimeFieldToStateMachineJobTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
