SELECT TOP 1
	[GlassCode],
	[Nvic],
	[VehicleTypeCode],
	[VehicleTypeDescription],
	[Year],
	[Month],
	[MakeCode],
	[MakeDescription],
	[FamilyCode],
	[FamilyDescription],
	[Variant],
	[Series],
	[Body],
	[EngineType],
	[EngineVolume],
	[EngineSize],
	[Transmission],
	[Cylinders],
	[LowTradeValue],
	[HighTradeValue],
	[DealerUsedValue],
	[BelowAverageValue],
	[AverageValue],
	[AboveAverageValue],
	[NewPrice],
	[UsedPrice],
	CONCAT([Series], ' ', [Variant], ' ', [Body], ' ', [Transmission], ' ', [EngineSize]) AS VehicleDescription
FROM [GlassGuide].[GG_Vehicle_View]
WHERE [GlassCode] = @GlassCode