// <copyright file="Permission.cs" company="uBind">
// Copyright (c) uBind. All rights reserved.
// </copyright>

// If you edit this file, you must remove this line and then do proper null checking
#pragma warning disable CS8600, CS8625, CS8629, CS8618, CS8605, CS8604, CS8601, CS8602, CS8603, CS8622, CS8619, CS8767, CS8620, CS8765

namespace UBind.Domain.Permissions
{
    using System.ComponentModel;
    using UBind.Domain.Attributes;

    /// <summary>
    /// Permissions are used to restrict access to particular features in the application.
    /// </summary>
    public enum Permission
    {
        [Concern(Concern.MyAccount)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("View My Account")]
        [EntityType(EntityType.User)]
        [PermissionType(PermissionType.Read)]
        ViewMyAccount = 1,

        [Concern(Concern.MyAccount)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("Edit My Account")]
        [EntityType(EntityType.User)]
        [PermissionType(PermissionType.Write)]
        EditMyAccount = 2,

        [Concern(Concern.Users)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Users")]
        [EntityType(EntityType.User)]
        [PermissionType(PermissionType.Read)]
        ViewUsers = 3,

        [Concern(Concern.Users)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Users")]
        [EntityType(EntityType.User)]
        [PermissionType(PermissionType.Write)]
        ManageUsers = 4,

        [Concern(Concern.Users)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Tenant Admin Users")]
        [EntityType(EntityType.User)]
        [PermissionType(PermissionType.Write)]
        ManageTenantAdminUsers = 5,

        [Concern(Concern.Users)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Organisation Admin Users")]
        [EntityType(EntityType.User)]
        [PermissionType(PermissionType.Write)]
        ManageOrganisationAdminUsers = 6,

        [Concern(Concern.Users)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [Description("Manage Master Admin Users")]
        [EntityType(EntityType.User)]
        [PermissionType(PermissionType.Write)]
        ManageMasterAdminUsers = 7,

        [Concern(Concern.Roles)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Roles")]
        [EntityType(EntityType.Role)]
        [PermissionType(PermissionType.Read)]
        ViewRoles = 8,

        [Concern(Concern.Roles)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Roles")]
        [EntityType(EntityType.Role)]
        [PermissionType(PermissionType.Write)]
        ManageRoles = 9,

        [Concern(Concern.Quotes)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("View Quotes")]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Read)]
        ViewQuotes = 10,

        [Concern(Concern.Quotes)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("Manage Quotes")]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Write)]
        ManageQuotes = 11,

        [Concern(Concern.Quotes)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Endorse Quotes")]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Write)]
        EndorseQuotes = 12,

        [Concern(Concern.Quotes)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Review Quotes")]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Write)]
        ReviewQuotes = 13,

        [Concern(Concern.Quotes)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Export Quotes")]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Read)]
        ExportQuotes = 14,

        [Concern(Concern.QuoteVersions)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("View Quote Versions")]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Read)]
        ViewQuoteVersions = 15,

        [Concern(Concern.QuoteVersions)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("Manage Quote Versions")]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Write)]
        ManageQuoteVersions = 16,

        [Concern(Concern.Policies)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("View Policies")]
        [EntityType(EntityType.Policy)]
        [PermissionType(PermissionType.Read)]
        ViewPolicies = 17,

        [Concern(Concern.Policies)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Export Policies")]
        [EntityType(EntityType.Policy)]
        [PermissionType(PermissionType.Read)]
        ExportPolicies = 18,

        [Concern(Concern.Policies)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Import Policies")]
        [EntityType(EntityType.Policy)]
        [PermissionType(PermissionType.Write)]
        ImportPolicies = 19,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("View Claims")]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Read)]
        ViewClaims = 20,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("Manage Claims")]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Write)]
        ManageClaims = 21,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Acknowledge Claim Notifications")]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Write)]
        AcknowledgeClaimNotifications = 22,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Review Claims")]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Write)]
        ReviewClaims = 23,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Assess Claims")]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Write)]
        AssessClaims = 24,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Settle Claims")]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Write)]
        SettleClaims = 25,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Export Claims")]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Read)]
        ExportClaims = 26,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Import Claims")]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Write)]
        ImportClaims = 27,

        [Concern(Concern.Customers)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Customers")]
        [EntityType(EntityType.Customer)]
        [PermissionType(PermissionType.Read)]
        ViewCustomers = 28,

        [Concern(Concern.Customers)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Customers")]
        [EntityType(EntityType.Customer)]
        [PermissionType(PermissionType.Write)]
        ManageCustomers = 29,

        [Concern(Concern.Customers)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Import Customers")]
        [EntityType(EntityType.Customer)]
        [PermissionType(PermissionType.Write)]
        ImportCustomers = 30,

        [Concern(Concern.Messages)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("View Messages")]
        [EntityType(EntityType.Message)]
        [PermissionType(PermissionType.Read)]
        ViewMessages = 31,

        [Concern(Concern.Messages)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("Manage Messages")]
        [EntityType(EntityType.Message)]
        [PermissionType(PermissionType.Write)]
        ManageMessages = 32,

        [Concern(Concern.Reports)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Reports")]
        [EntityType(EntityType.Report)]
        [PermissionType(PermissionType.Read)]
        ViewReports = 33,

        [Concern(Concern.Reports)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Reports")]
        [EntityType(EntityType.Report)]
        [PermissionType(PermissionType.Write)]
        ManageReports = 34,

        [Concern(Concern.Reports)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Generate Reports")]
        [EntityType(EntityType.Report)]
        [PermissionType(PermissionType.Write)]
        GenerateReports = 35,

        [Concern(Concern.Environments)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("Access Development Data")]
        AccessDevelopmentData = 36,

        [Concern(Concern.Environments)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("Access Staging Data")]
        AccessStagingData = 37,

        [Concern(Concern.Environments)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("Access Production Data")]
        AccessProductionData = 38,

        [Concern(Concern.Tenants)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Master)]
        [Description("View Tenants")]
        [EntityType(EntityType.Tenant)]
        [PermissionType(PermissionType.Read)]
        ViewTenants = 39,

        [Concern(Concern.Tenants)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Master)]
        [Description("Manage Tenants")]
        [EntityType(EntityType.Tenant)]
        [PermissionType(PermissionType.Write)]
        ManageTenants = 40,

        [Concern(Concern.Organisations)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Organisations")]
        [EntityType(EntityType.Organisation)]
        [PermissionType(PermissionType.Read)]
        ViewOrganisations = 41,

        [Concern(Concern.Organisations)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Organisations")]
        [EntityType(EntityType.Organisation)]
        [PermissionType(PermissionType.Write)]
        ManageOrganisations = 42,

        [Concern(Concern.Organisations)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View All Organisations")]
        [EntityType(EntityType.Organisation)]
        [PermissionType(PermissionType.Read)]
        ViewAllOrganisations = 43,

        [Concern(Concern.Organisations)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage All Organisations")]
        [EntityType(EntityType.Organisation)]
        [PermissionType(PermissionType.Write)]
        ManageAllOrganisations = 44,

        [Concern(Concern.Products)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Products")]
        [EntityType(EntityType.Product)]
        [PermissionType(PermissionType.Read)]
        ViewProducts = 45,

        [Concern(Concern.Products)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Products")]
        [EntityType(EntityType.Product)]
        [PermissionType(PermissionType.Write)]
        ManageProducts = 46,

        [Concern(Concern.Releases)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Releases")]
        [EntityType(EntityType.Release)]
        [PermissionType(PermissionType.Read)]
        ViewReleases = 47,

        [Concern(Concern.Releases)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Releases")]
        [EntityType(EntityType.Release)]
        [PermissionType(PermissionType.Write)]
        ManageReleases = 48,

        [Concern(Concern.Releases)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Promote Releases To Staging")]
        [EntityType(EntityType.Release)]
        [PermissionType(PermissionType.Write)]
        PromoteReleasesToStaging = 49,

        [Concern(Concern.Releases)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Promote Releases To Production")]
        [EntityType(EntityType.Release)]
        [PermissionType(PermissionType.Write)]
        PromoteReleasesToProduction = 50,

        [Concern(Concern.Portals)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Portals")]
        [EntityType(EntityType.Portal)]
        [PermissionType(PermissionType.Read)]
        ViewPortals = 51,

        [Concern(Concern.Portals)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Portals")]
        [EntityType(EntityType.Portal)]
        [PermissionType(PermissionType.Write)]
        ManagePortals = 52,

        [Concern(Concern.Imports)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Import Data")]
        [PermissionType(PermissionType.Write)]
        ImportData = 53,

        [Concern(Concern.Maintenance)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Replay Integration Events")]
        [PermissionType(PermissionType.Write)]
        ReplayIntegrationEvents = 54,

        [Concern(Concern.BackgroundJobs)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Background Jobs")]
        [PermissionType(PermissionType.Read)]
        ViewBackgroundJobs = 55,

        [Concern(Concern.BackgroundJobs)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Background Jobs")]
        [PermissionType(PermissionType.Write)]
        ManageBackgroundJobs = 56,

        [Concern(Concern.AdditionalProperties)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Additional Property Values")]
        [PermissionType(PermissionType.Read)]
        [MatchesStringValue("ViewAdditionalProperties")] // for backwards compatibility
        ViewAdditionalPropertyValues = 57,

        [Concern(Concern.AdditionalProperties)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Edit Additional Property Values")]
        [PermissionType(PermissionType.Write)]
        [MatchesStringValue("EditAdditionalProperties")] // for backwards compatibility
        EditAdditionalPropertyValues = 58,

        [Concern(Concern.AdditionalProperties)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterProductDeveloper)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Additional Property Definitions")]
        [PermissionType(PermissionType.Write)]
        [PermissionType(PermissionType.Read)]
        [MatchesStringValue("ManageAdditionalPropertiesDefinition")] // for backwards compatibility
        ManageAdditionalPropertyDefinitions = 59,

        [Concern(Concern.StartupJobs)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [Description("Manage Startup Jobs")]
        [PermissionType(PermissionType.Write)]
        ManageStartupJobs = 60,

        [Concern(Concern.Policies)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Customer)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Customer)]
        [Description("Manage Policies")]
        [EntityType(EntityType.Policy)]
        [PermissionType(PermissionType.Write)]
        ManagePolicies = 61,

        [Concern(Concern.Customers)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Customer Accounts")]
        [EntityType(EntityType.Customer)]
        [PermissionType(PermissionType.Read)]
        ViewCustomerAccounts = 62,

        [Concern(Concern.Customers)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Customer Accounts")]
        [EntityType(EntityType.Customer)]
        [PermissionType(PermissionType.Write)]
        ManageCustomerAccounts = 63,

        [Concern(Concern.Customers)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Customer)]
        [PermissionType(PermissionType.Read)]
        [Description("View All Customers")]
        ViewAllCustomers = 64,

        [Concern(Concern.Quotes)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Read)]
        [Description("View All Quotes")]
        ViewAllQuotes = 65,

        [Concern(Concern.Quotes)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Read)]
        [Description("View All Quotes From All Organisations")]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ViewAllQuotesFromAllOrganisations = 66,

        [Concern(Concern.Policies)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Policy)]
        [PermissionType(PermissionType.Read)]
        [Description("View All Policies")]
        ViewAllPolicies = 67,

        [Concern(Concern.Policies)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Policy)]
        [PermissionType(PermissionType.Read)]
        [Description("View All Policies From All Organisations")]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ViewAllPoliciesFromAllOrganisations = 68,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Read)]
        [Description("View All Claims")]
        ViewAllClaims = 69,

        [Concern(Concern.Users)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Master)]
        [Description("View Users From Other Organisations")]
        [EntityType(EntityType.User)]
        [PermissionType(PermissionType.Read)]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ViewUsersFromOtherOrganisations = 70,

        [Concern(Concern.Users)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterSupportAgent)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Master)]
        [Description("Manage Users For Other Organisations")]
        [EntityType(EntityType.User)]
        [PermissionType(PermissionType.Write)]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ManageUsersForOtherOrganisations = 71,

        [Concern(Concern.Roles)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View Roles From All Organisations")]
        [EntityType(EntityType.Role)]
        [PermissionType(PermissionType.Read)]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ViewRolesFromAllOrganisations = 72,

        [Concern(Concern.Roles)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage Roles For All Organisations")]
        [EntityType(EntityType.Role)]
        [PermissionType(PermissionType.Write)]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ManageRolesForAllOrganisations = 73,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Read)]
        [Description("View All Claims From All Organisations")]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ViewAllClaimsFromAllOrganisations = 74,

        [Concern(Concern.Customers)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Customer)]
        [PermissionType(PermissionType.Write)]
        [Description("Manage All Customers")]
        ManageAllCustomers = 75,

        [Concern(Concern.Quotes)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Write)]
        [Description("Manage All Quotes")]
        ManageAllQuotes = 76,

        [Concern(Concern.Quotes)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Quote)]
        [PermissionType(PermissionType.Write)]
        [Description("Manage All Quotes For All Organisations")]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ManageAllQuotesForAllOrganisations = 77,

        [Concern(Concern.Policies)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Policy)]
        [PermissionType(PermissionType.Write)]
        [Description("Manage All Policies")]
        ManageAllPolicies = 78,

        [Concern(Concern.Policies)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Policy)]
        [PermissionType(PermissionType.Write)]
        [Description("Manage All Policies For All Organisations")]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ManageAllPoliciesForAllOrganisations = 79,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Write)]
        [Description("Manage All Claims")]
        ManageAllClaims = 80,

        [Concern(Concern.Claims)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Claim)]
        [PermissionType(PermissionType.Write)]
        [Description("Manage All Claims For All Organisations")]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ManageAllClaimsForAllOrganisations = 81,

        [Concern(Concern.Messages)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("View All Messages")]
        [EntityType(EntityType.Message)]
        [PermissionType(PermissionType.Read)]
        ViewAllMessages = 82,

        [Concern(Concern.Messages)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForRoleType(RoleType.Master)]
        [PermittedForRoleType(RoleType.Client)]
        [Description("Manage All Messages")]
        [EntityType(EntityType.Message)]
        [PermissionType(PermissionType.Write)]
        ManageAllMessages = 83,

        [Concern(Concern.DataTableDefinition)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Master)]
        [PermissionType(PermissionType.Read)]
        [Description("View Data Tables")]
        ViewDataTables = 84,

        [Concern(Concern.DataTableDefinition)]
        [PermittedForDefaultRole(DefaultRole.MasterAdmin)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [PermittedForRoleType(RoleType.Client)]
        [PermittedForRoleType(RoleType.Master)]
        [PermissionType(PermissionType.Write)]
        [Description("Manage Data Tables")]
        ManageDataTables = 85,

        [Concern(Concern.Customers)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Customer)]
        [PermissionType(PermissionType.Read)]
        [Description("View All Customers From All Organisations")]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ViewAllCustomersFromAllOrganisations = 86,

        [Concern(Concern.Customers)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Customer)]
        [PermissionType(PermissionType.Write)]
        [Description("Manage All Customers For All Organisations")]
        [PermissionAvailableToDefaultOrganisationUsersOnly]
        ManageAllCustomersForAllOrganisations = 87,

        [Concern(Concern.Policies)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Policy)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.UnderWriter)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [Description("Manage Policy Numbers")]
        [PermissionType(PermissionType.Write)]
        ManagePolicyNumbers = 88,

        [Concern(Concern.Claims)]
        [PermittedForRoleType(RoleType.Client)]
        [EntityType(EntityType.Claim)]
        [PermittedForDefaultRole(DefaultRole.TenantAdmin)]
        [PermittedForDefaultRole(DefaultRole.OrganisationAdmin)]
        [PermittedForDefaultRole(DefaultRole.Broker)]
        [PermittedForDefaultRole(DefaultRole.ClaimsAgent)]
        [PermittedForDefaultRole(DefaultRole.ClientProductDeveloper)]
        [Description("Manage Claim Numbers")]
        [PermissionType(PermissionType.Write)]
        ManageClaimNumbers = 89,
    }
}
