// <copyright file="ProductConfiguration.cs" company="uBind">
// Copyright (c) uBind. All rights reserved.
// </copyright>

// If you edit this file, you must remove this line and then do proper null checking
#pragma warning disable CS8600, CS8625, CS8629, CS8618, CS8605, CS8604, CS8601, CS8602, CS8603, CS8622, CS8619, CS8767, CS8620, CS8765

namespace UBind.Domain.Entities
{
    using System;
    using Newtonsoft.Json;
    using UBind.Domain.Aggregates.Claim.Workflow;
    using UBind.Domain.Aggregates.Quote;
    using UBind.Domain.Aggregates.Quote.DataLocator;
    using UBind.Domain.Aggregates.Quote.Workflow;
    using UBind.Domain.Configuration;
    using UBind.Domain.NumberGenerators;

    /// <inheritdoc />
    public class ProductConfiguration : IProductConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductConfiguration"/> class.
        /// </summary>
        /// <param name="productConfigurationJson">The workflow to be used.</param>
        /// <param name="formDataSchema">The form data schema.</param>
        public ProductConfiguration(string productConfigurationJson, FormDataSchema formDataSchema)
        {
            JsonConvert.PopulateObject(productConfigurationJson, this);
            this.FormDataSchema = formDataSchema;
        }

        /// <summary>
        /// Gets the form data schema.
        /// </summary>
        public FormDataSchema FormDataSchema { get; private set; }

        /// <summary>
        /// Gets the quote number source.
        /// </summary>
        public NumberSource QuoteNumberSource { get; private set; } = NumberSource.AutoGenerated;

        /// <inheritdoc/>
        public NumberObfuscationMethod NumberObfuscationMethod { get; private set; } = NumberObfuscationMethod.SixDigitAlphabetic;

        /// <summary>
        /// Gets the quote workflow.
        /// </summary>
        [JsonProperty]
        public QuoteWorkflow QuoteWorkflow { get; private set; }

        /// <summary>
        /// Gets the quote workflow.
        /// </summary>
        [JsonProperty]
        public ClaimWorkflow ClaimWorkflow { get; private set; }

        /// <summary>
        /// Gets the configured quote data locations.
        /// </summary>
        [JsonProperty]
        public ConfiguredQuoteDatumLocations QuoteDatumLocations { get; private set; }

        /// <summary>
        /// Gets the configured quote data locations.
        /// </summary>
        [JsonProperty]
        public DataLocators DataLocators { get; private set; }

        /// <summary>
        /// Gets context entities which are loaded for all quote transaction types.
        /// </summary>
        [JsonProperty]
        public ContextEntities ContextEntities { get; private set; }

        /// <inheritdoc />
        IClaimWorkflow IProductConfiguration.ClaimWorkflow => this.ClaimWorkflow;

        /// <inheritdoc />
        IQuoteWorkflow IProductConfiguration.QuoteWorkflow => this.QuoteWorkflow;

        /// <inheritdoc />
        IQuoteDatumLocations IDataLocatorConfig.QuoteDataLocations => this.QuoteDatumLocations;

        /// <inheritdoc />
        IFormDataSchema IProductConfiguration.FormDataSchema => this.FormDataSchema;

        /// <inheritdoc />
        DataLocators IDataLocatorConfig.DataLocators => this.DataLocators;

        /// <inheritdoc />
        IContextEntities IProductConfiguration.ContextEntities => this.ContextEntities;

        /// <summary>
        /// Sets the quote data location from the old quoteDataLocator property, if it exists.
        /// This method is deprecated. It used to load a QuoteDataLocator directly, but now
        /// we are just loading the quoteDataLocations, and consumers can create a specific
        /// QuoteDataLocator if they wish.
        /// </summary>
        [Obsolete("Deprecated. Instead we will use QuoteDatumLocations")]
        [JsonProperty]
        [System.Diagnostics.CodeAnalysis.SuppressMessage(
            "CodeQuality",
            "IDE0051:Remove unused private members",
            Justification = "Used by Json Deserialisation for backwards compatibility.")]
        private ConfiguredQuoteDatumLocations QuoteDataLocator
        {
            set { this.QuoteDatumLocations = value; }
        }
    }
}
