// <auto-generated />
#pragma warning disable 1591
namespace UBind.Persistence
{
    using System;
    using System.Data.Entity.Migrations;
    using UBind.Persistence.Migrations.Extensions;

    public partial class AddEffectiveDate : DbMigration
    {
        public override void Up()
        {
            DropIndex("dbo.Perils", "AK_GnafPidIndex");
            DropPrimaryKey("dbo.Perils");
            this.AddColumnIfNotExists("dbo.Perils", "EffectiveDate", c => c.DateTime(nullable: false, defaultValue: new DateTime(2020, 1, 1)));
            AddPrimaryKey("dbo.Perils", new[] { "GnafPid", "EffectiveDate" });
            CreateIndex("dbo.Perils", new[] { "GnafPid", "EffectiveDate" }, unique: true, name: "AK_GnafPidIndex");
        }
        
        public override void Down()
        {
            DropIndex("dbo.Perils", "AK_GnafPidIndex");
            DropPrimaryKey("dbo.Perils");
            DropColumn("dbo.Perils", "EffectiveDate");
            AddPrimaryKey("dbo.Perils", "GnafPid");
            CreateIndex("dbo.Perils", "GnafPid", unique: true, name: "AK_GnafPidIndex");
        }
    }
}
